### ISSUE TITLE
[Bug] Negative variance when predicting KISS-GP output in DKL framework

### ISSUE THREAD

**Issue by francescovaroli** [cornellius-gp/gpytorch#1037]
# 🐛 Bug

Hi, I've implemented a DKL model as described in the Tutorial here https://gpytorch.readthedocs.io/en/latest/examples/06_PyTorch_NN_Integration_DKL/KISSGP_Deep_Kernel_Regression_CUDA.html .
After training the model for a few iterations (in each iteration I train the model for 30 epochs on a different dataset of 30 functions), the model start returning ```nan``` stddevs, due to a negative variance in the prediction. While debugging I backtraced the first appearance of a negative-definite covariance matrix, when the KISS-GP is computing the  exact_predictive_covar given the joint distribution of train and test data.
in file gpytorch/models/exact_prediction_strategies.py at line 264
 ```
test_train_covar = delazify(test_train_covar)
train_test_covar = test_train_covar.transpose(-1, -2)
covar_correction_rhs = train_train_covar.inv_matmul(train_test_covar)
# For efficiency
if torch.is_tensor(test_test_covar):
     # We can use addmm in the 2d case
     if test_test_covar.dim() == 2:
         return lazify(torch.addmm(1, test_test_covar, -1, test_train_covar, covar_correction_rhs))
     else:
        return lazify(test_test_covar + test_train_covar @ covar_correction_rhs.mul(-1))
# In other cases - we'll use the standard infrastructure
else:
-->    return test_test_covar + MatmulLazyTensor(test_train_covar, covar_correction_rhs.mul(-1))
```
This behaviour happens using both  
```python gpytorch.settings.use_toeplitz(), gpytorch.settings.fast_pred_var()```  set as True / False

This only happens after some training of the Feature Extractor and GP.

The data (4D input) is mapped by the NN to a 1D space and normalized in [0, 1].
Also, I'm using the model to predict a single target point, given a context set of ~100-2000 points. 

## To reproduce

Unfortunately I cannot share my data since it's gathered dynamically by another process, however I know it is Gaussian distributed and I noticed that the bug appears earlier when the variance of the data is smaller.
```python

import gpytorch
import torch
import numpy as np

class LargeFeatureExtractor(torch.nn.Sequential):
    def __init__(self, x_dim, h_dim, out_dim):
        super(LargeFeatureExtractor, self).__init__()
        self.add_module('linear1', torch.nn.Linear(x_dim, h_dim))  # default h_dim = 256
        self.add_module('relu1', torch.nn.ReLU())
        self.add_module('linear2', torch.nn.Linear(h_dim, out_dim))


class GPRegressionModel(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood, h_dim, z_dim, name_id, scaling='uniform', grid_size=None):
        super(GPRegressionModel, self).__init__(train_x, train_y, likelihood)
        if grid_size is None:
            grid_size = gpytorch.utils.grid.choose_grid_size(train_x)
            print('grid_size:', grid_size)
        self.mean_module = gpytorch.means.ConstantMean()
        self.covar_module = gpytorch.kernels.GridInterpolationKernel(gpytorch.kernels.ScaleKernel(
            gpytorch.kernels.RBFKernel(ard_num_dims=z_dim)), num_dims=z_dim, grid_size=grid_size)
        self.likelihood = likelihood
        _, num_points, x_dim = train_x.size()
        self.feature_extractor = LargeFeatureExtractor(x_dim, h_dim, z_dim)
        self.scaling = scaling
        self.id = name_id

    def project(self, x):
        # We're first putting our data through a deep net (feature extractor)
        # We're also scaling the features so that they're nice values
        projected_x = self.feature_extractor(x.squeeze(0))

        if self.scaling == 'uniform':
            projected_x = projected_x - projected_x.min(-2)[0]
            z = projected_x / projected_x.max(-2)[0]

        elif self.scaling == 'normal':
            z = (projected_x - projected_x.mean()) / projected_x.std()

        elif self.scaling is None:
            z = projected_x

        z[torch.isnan(z)] = 10000
        return z

    def forward(self, x):

        z = self.project(x)
        mean_x = self.mean_module(z)
        covar_x = self.covar_module(z)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)


def context_target_split(x, y, num_context, num_extra_target):

    num_points = x.shape[1]
    # Sample locations of context and target points
    locations = np.random.choice(num_points,
                                 size=num_context + num_extra_target,
                                 replace=False)
    x_context = x[:, locations[:num_context], :]
    y_context = y[:, locations[:num_context], :]
    x_target = x[:, locations[num_context:], :]
    y_target = y[:, locations[num_context:], :]
    return x_context, y_context, x_target, y_target

epochs = 30
x_init = torch.randn([1, 1000, 4])
y_init = torch.randn([1, 1000, 1])

likelihood = gpytorch.likelihoods.GaussianLikelihood()  # noise_constraint=gpytorch.constraints.LessThan(args.noise)
model = GPRegressionModel(x_init, y_init.view(-1), likelihood,
                          h_dim=200, z_dim=1, name_id='DKL', scaling='uniform')
mll = gpytorch.mlls.ExactMarginalLogLikelihood(model.likelihood, model)


optimizer = torch.optim.Adam([
    {'params': model.feature_extractor.parameters()},
    {'params': model.covar_module.parameters()},
    {'params': model.mean_module.parameters()},
    {'params': model.likelihood.parameters()}], lr=0.01)

## train
for epoch in range(epochs):
    epoch_loss = 0.
    for i, data in enumerate(data_loader):

        # Zero backprop gradients
        optimizer.zero_grad()
        # Get output from model
        x, y, num_points = data  # add , num_points
        # divide context (N-1) and target (1)
        x_context, y_context, x_target, y_target = context_target_split(x[:, :num_points, :],
                                                                        y[:, :num_points, :],
                                                                        num_points.item() - 1, 1)

        # I want the model to learn predicting a target set given a context set, however the negative variance appears in the prediction even when the model is trained on the context set as shown i the tutorial
        model.set_train_data(inputs=x_context, targets=y_context.view(-1), strict=False)
        model.eval()
        model.likelihood.eval()
        predictions = model(x_target)
        model.train()
        model.likelihood.train()

        loss = -mll(predictions, y_target.view(-1))
        loss.backward()
        optimizer.step()
        epoch_loss += loss.item()
        avg_loss = epoch_loss / len(data_loader)
    if epoch % 10 == 0 or epoch == epochs - 1:
        print("Epoch: {}, Avg_loss: {}".format(epoch, avg_loss))

## testing
model.set_train_data(inputs=x_context, targets=y_context.view(-1), strict=False)
p_y_pred = model(x_target)
```

** Stack trace/error message **
```
use_toeplitz(False)
Traceback (most recent call last):
  File "/home/francesco/anaconda3/envs/MasterThesis/lib/python3.7/site-packages/gpytorch/utils/cholesky.py", line 24, in psd_safe_cholesky
    L = torch.cholesky(A, upper=upper, out=out)
RuntimeError: cholesky_cpu: For batch 0: U(1,1) is zero, singular U.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/francesco/PycharmProjects/MasterThesis/Master-Thesis/Deep_Kernel_Learning/DKModel.py", line 92, in train_rl
    predictions = self.model(x_target)
  File "/home/francesco/anaconda3/envs/MasterThesis/lib/python3.7/site-packages/gpytorch/models/exact_gp.py", line 326, in __call__
    predictive_mean, predictive_covar = self.prediction_strategy.exact_prediction(full_mean, full_covar)
  File "/home/francesco/anaconda3/envs/MasterThesis/lib/python3.7/site-packages/gpytorch/models/exact_prediction_strategies.py", line 508, in exact_prediction
    self.exact_predictive_mean(test_mean, test_train_covar),
  File "/home/francesco/anaconda3/envs/MasterThesis/lib/python3.7/site-packages/gpytorch/models/exact_prediction_strategies.py", line 513, in exact_predictive_mean
    precomputed_cache = self.mean_cache
  File "/home/francesco/anaconda3/envs/MasterThesis/lib/python3.7/site-packages/gpytorch/utils/memoize.py", line 34, in g
    add_to_cache(self, cache_name, method(self, *args, **kwargs))
  File "/home/francesco/anaconda3/envs/MasterThesis/lib/python3.7/site-packages/gpytorch/models/exact_prediction_strategies.py", line 419, in mean_cache
    train_train_covar_inv_labels = train_train_covar_with_noise.inv_matmul(mean_diff)
  File "/home/francesco/anaconda3/envs/MasterThesis/lib/python3.7/site-packages/gpytorch/lazy/lazy_tensor.py", line 939, in inv_matmul
    return func.apply(self.representation_tree(), False, right_tensor, *self.representation())
  File "/home/francesco/anaconda3/envs/MasterThesis/lib/python3.7/site-packages/gpytorch/functions/_inv_matmul.py", line 47, in forward
    solves = _solve(lazy_tsr, right_tensor)
  File "/home/francesco/anaconda3/envs/MasterThesis/lib/python3.7/site-packages/gpytorch/functions/_inv_matmul.py", line 11, in _solve
    return lazy_tsr._cholesky()._cholesky_solve(rhs)
  File "/home/francesco/anaconda3/envs/MasterThesis/lib/python3.7/site-packages/gpytorch/utils/memoize.py", line 34, in g
    add_to_cache(self, cache_name, method(self, *args, **kwargs))
  File "/home/francesco/anaconda3/envs/MasterThesis/lib/python3.7/site-packages/gpytorch/lazy/lazy_tensor.py", line 419, in _cholesky
    cholesky = psd_safe_cholesky(evaluated_mat).contiguous()
  File "/home/francesco/anaconda3/envs/MasterThesis/lib/python3.7/site-packages/gpytorch/utils/cholesky.py", line 30, in psd_safe_cholesky
    f"cholesky_cpu: {isnan.sum().item()} of {A.numel()} elements of the {A.shape} tensor are NaN."
gpytorch.utils.errors.NanError: cholesky_cpu: 900 of 900 elements of the torch.Size([1, 30, 30]) tensor are NaN.

Process finished with exit code 1

use_toeplitz(True)
Traceback (most recent call last):
  File "/home/francesco/anaconda3/envs/MasterThesis/lib/python3.7/site-packages/gpytorch/models/exact_gp.py", line 326, in __call__
    predictive_mean, predictive_covar = self.prediction_strategy.exact_prediction(full_mean, full_covar)
  File "/home/francesco/anaconda3/envs/MasterThesis/lib/python3.7/site-packages/gpytorch/models/exact_prediction_strategies.py", line 508, in exact_prediction
    self.exact_predictive_mean(test_mean, test_train_covar),
  File "/home/francesco/anaconda3/envs/MasterThesis/lib/python3.7/site-packages/gpytorch/models/exact_prediction_strategies.py", line 513, in exact_predictive_mean
    precomputed_cache = self.mean_cache
  File "/home/francesco/anaconda3/envs/MasterThesis/lib/python3.7/site-packages/gpytorch/utils/memoize.py", line 34, in g
    add_to_cache(self, cache_name, method(self, *args, **kwargs))
  File "/home/francesco/anaconda3/envs/MasterThesis/lib/python3.7/site-packages/gpytorch/models/exact_prediction_strategies.py", line 419, in mean_cache
    train_train_covar_inv_labels = train_train_covar_with_noise.inv_matmul(mean_diff)
  File "/home/francesco/anaconda3/envs/MasterThesis/lib/python3.7/site-packages/gpytorch/lazy/lazy_tensor.py", line 939, in inv_matmul
    return func.apply(self.representation_tree(), False, right_tensor, *self.representation())
  File "/home/francesco/anaconda3/envs/MasterThesis/lib/python3.7/site-packages/gpytorch/functions/_inv_matmul.py", line 47, in forward
    solves = _solve(lazy_tsr, right_tensor)
  File "/home/francesco/anaconda3/envs/MasterThesis/lib/python3.7/site-packages/gpytorch/functions/_inv_matmul.py", line 11, in _solve
    return lazy_tsr._cholesky()._cholesky_solve(rhs)
  File "/home/francesco/anaconda3/envs/MasterThesis/lib/python3.7/site-packages/gpytorch/utils/memoize.py", line 34, in g
    add_to_cache(self, cache_name, method(self, *args, **kwargs))
  File "/home/francesco/anaconda3/envs/MasterThesis/lib/python3.7/site-packages/gpytorch/lazy/lazy_tensor.py", line 407, in _cholesky
    evaluated_mat = evaluated_kern_mat.evaluate()
  File "/home/francesco/anaconda3/envs/MasterThesis/lib/python3.7/site-packages/gpytorch/utils/memoize.py", line 34, in g
    add_to_cache(self, cache_name, method(self, *args, **kwargs))
  File "/home/francesco/anaconda3/envs/MasterThesis/lib/python3.7/site-packages/gpytorch/lazy/sum_lazy_tensor.py", line 62, in evaluate
    return sum(lazy_tensor.evaluate() for lazy_tensor in self.lazy_tensors)
  File "/home/francesco/anaconda3/envs/MasterThesis/lib/python3.7/site-packages/gpytorch/lazy/sum_lazy_tensor.py", line 62, in <genexpr>
    return sum(lazy_tensor.evaluate() for lazy_tensor in self.lazy_tensors)
  File "/home/francesco/anaconda3/envs/MasterThesis/lib/python3.7/site-packages/gpytorch/utils/memoize.py", line 34, in g
    add_to_cache(self, cache_name, method(self, *args, **kwargs))
  File "/home/francesco/anaconda3/envs/MasterThesis/lib/python3.7/site-packages/gpytorch/lazy/lazy_tensor.py", line 882, in evaluate
    res = self.matmul(eye)
  File "/home/francesco/anaconda3/envs/MasterThesis/lib/python3.7/site-packages/gpytorch/lazy/interpolated_lazy_tensor.py", line 405, in matmul
    base_res = self.base_lazy_tensor.matmul(right_interp_res)
  File "/home/francesco/anaconda3/envs/MasterThesis/lib/python3.7/site-packages/gpytorch/lazy/lazy_tensor.py", line 1102, in matmul
    return func.apply(self.representation_tree(), other, *self.representation())
  File "/home/francesco/anaconda3/envs/MasterThesis/lib/python3.7/site-packages/gpytorch/functions/_matmul.py", line 21, in forward
    res = lazy_tsr._matmul(rhs)
  File "/home/francesco/anaconda3/envs/MasterThesis/lib/python3.7/site-packages/gpytorch/lazy/kronecker_product_lazy_tensor.py", line 87, in _matmul
    res = _matmul(self.lazy_tensors, self.shape, rhs.contiguous())
  File "/home/francesco/anaconda3/envs/MasterThesis/lib/python3.7/site-packages/gpytorch/lazy/kronecker_product_lazy_tensor.py", line 26, in _matmul
    factor = lazy_tensor._matmul(res)
  File "/home/francesco/anaconda3/envs/MasterThesis/lib/python3.7/site-packages/gpytorch/lazy/toeplitz_lazy_tensor.py", line 30, in _matmul
    return sym_toeplitz_matmul(self.column, rhs)
  File "/home/francesco/anaconda3/envs/MasterThesis/lib/python3.7/site-packages/gpytorch/utils/toeplitz.py", line 163, in sym_toeplitz_matmul
    return toeplitz_matmul(toeplitz_column, toeplitz_column, tensor)
  File "/home/francesco/anaconda3/envs/MasterThesis/lib/python3.7/site-packages/gpytorch/utils/toeplitz.py", line 120, in toeplitz_matmul
    "Got: c[0]={} and r[0]={}".format(toeplitz_column[0], toeplitz_row[0])
RuntimeError: The first column and first row of the Toeplitz matrix should have the same first element, otherwise the value of T[0,0] is ambiguous. Got: c[0]=tensor([nan, nan, nan, nan, nan, nan], requires_grad=True) and r[0]=tensor([nan, nan, nan, nan, nan, nan], requires_grad=True)

Process finished with exit code 1

```

## Expected Behavior

 I guess The variance should approach zero but not get negtive

## System information

**Please complete the following information:**
-  GPyTorch Version 1.0.1
- PyTorch Version 1.3.0
-  Linux Ubuntu 18.04.3 LTS

## Additional context
I may be missing some settings needed to avoid this behaviour

**Comment by gpleiss** [comment]
Thanks for the detailed stack trace @francescovaroli ! My guess - given that this behavior occurs with both `fast_pred_var=True/False` - is that your data might be creating a kernel matrix that is ill-conditioned.

Unfortunately - we can't really add a check for bad covariances into GPyTorch. Since we're dealing with covariance matrices and not variances, we'd have to check that the covariance matrix is positive definite. That's too expensive to do in practice.

Some thoughts about ways to fix this problem:

1) My guess, given these errors, is that your Xs are too close together. If you have two or more X values that are nearly-similar, then you'll get a singular kernel matrix which would cause these errors. Can you add a bit of Gaussian noise to your Xs, or make sure that you don't contain any duplicate Xs in your training set?
2) What are the likelihood noise values: if they're very small, then maybe try adding a constraint to the noise to make it something non-zero (i.e. make it larger than 1e-3)

**Comment by francescovaroli** [comment]
Thanks for your quick reply @gpleiss ! 
I understand that a check on the covariance is not feasible, I just wanted to make sure there was no easy way to avoid my problem.
 
1. Yes, my context set probably contains very similar Xs values. However the error appears after some training, could that be due to the Feature Extractor network learning to output too similar z-projections? is there something I can do in the z-normalization in your opinion?

2. I've done that, but it doesn't seem to help. 

Another problem I noticed is that the lengthscale parameter of the RBF kernel is never updated during training, do you see a clear reason why that could be happening?

During training
```
print('epoch %d - Loss: %.3f   lengthscale: %.3f  outpuscale: %.3f   noise: %.3f' % (epoch, loss.item(),
        model.covar_module.base_kernel.base_kernel.lengthscale.item(),
        model.covar_module.base_kernel.outputscale.item(),
        model.likelihood.noise.item()))
```
returns:
![Schermata da 2020-02-03 15-31-32](https://user-images.githubusercontent.com/32619941/73661876-230ab180-469b-11ea-9b8c-42bc0cde46cc.png)
