### ISSUE TITLE
Run time error for loading state_dict in MultitaskGPModel

### ISSUE THREAD

**Issue by christae** [cornellius-gp/gpytorch#1135]
# 🐛 Bug

When I load a state_dict file to my Multi-Task GP, I get a run time error. 

## To reproduce

** Code snippet to reproduce **
```python
state_dict = torch.load("/Users/taechri/Desktop/MDPA/GPR/GPRmodels/AuxModel/MultiOutput/SixOutput/model_six"
                            "outputs_final.pth")
likelihood = gpytorch.likelihoods.GaussianLikelihood(num_tasks=6)

model = MultitaskGPModel(features_train, labels_train, likelihood)
model.load_state_dict(state_dict)
```

** Stack trace/error message **
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-5da8b31b95da>", line 1, in <module>
    runfile('/Users/taechri/Desktop/MDPA/GPR/Code/designGeoDict_Multi.py', wdir='/Users/taechri/Desktop/MDPA/GPR/Code')
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/taechri/Desktop/MDPA/GPR/Code/designGeoDict_Multi.py", line 113, in <module>
    model.load_state_dict(state_dict)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for MultitaskGPModel:
	Unexpected key(s) in state_dict: "likelihood.raw_noise". 
	size mismatch for likelihood.noise_covar.raw_noise: copying a param with shape torch.Size([6]) from checkpoint, the shape in current model is torch.Size([1]).

## Expected Behavior

I expected the terminal to output IncompatibleKeys(missing_keys=[]. unexpected_keys=[]), as demonstrated by the saving and loading models documentation. 

## System information

**Please complete the following information:**
-  1.0.1
-  1.5.0
-  MacOSx

**Comment by gpleiss** [comment]
I imagine that the issue is because the likelihood or the model doesn't match what you have stored in the state dict? I imagine you should be using `MultitaskGaussianLikelihood` instead of `GaussianLikelihood`
