### ISSUE TITLE
[Bug] CG terminated in 1000 iterations warning

### ISSUE THREAD

**Issue by jeffwillette** [cornellius-gp/gpytorch#1220]
# 🐛 Bug

- I am using a UCI dataset witht he exact GP model form the docs
- the data and labels are standard normalized

I have read from other threads that this may be cause by not normalizing the data, but I have my data normalized. This only happens towards the end of 1000 iterations and I am not sure exactly what is causing the error. It feels like it must be due to some kind of over/underflow but I am not sure. 

** Code snippet to reproduce **
```python
import numpy as np  # type: ignore
import torch
from gpytorch.likelihoods import GaussianLikelihood  # type: ignore
from gpytorch.mlls import ExactMarginalLogLikelihood  # type: ignore
from tqdm import tqdm  # type: ignore

from models.gp import ExactGP
from utils import Args, Stats


def train(args: Args, run: int) -> Stats:
    if args.train_set is None or args.test_set is None:
        raise ValueError("train or test set cannot be None")

    likelihood = GaussianLikelihood().double()
    model = ExactGP(args.train_set.dataset.x, args.train_set.dataset.y, likelihood).to(args.device).double()  # type: ignore

    mll = ExactMarginalLogLikelihood(likelihood, model)
    optimizer = torch.optim.Adam([{"params": model.parameters()}], lr=1e-2)

    loss_log = tqdm(total=0, bar_format="train: {desc}", position=2, leave=False)

    for i in range(1000):
        model.train()
        likelihood.train()

        x, y = (
            args.train_set.dataset.x.to(args.device).double(),  # type: ignore
            args.train_set.dataset.y.to(args.device).double(),  # type: ignore
        )

        output = model(x)
        loss = -mll(output, y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        model.eval()
        likelihood.eval()

        x, y = (
            args.test_set.dataset.x.to(args.device).double(),  # type: ignore
            args.test_set.dataset.y.to(args.device).double(),  # type: ignore
        )

        yhat = likelihood(model(x))
        ll = mll(yhat, y) - np.log(args.test_set.dataset.y_sigma)  # type: ignore

        desc = (
            f"iter: {i} mll: {-loss.item()} test ll: {ll.item()}"
            f"ls: {model.covar_module.base_kernel.lengthscale.item()} "
            f"noise: {model.likelihood.noise.item()}"
        )
        loss_log.set_description(desc)

    t = Stats()
    return t
```

** Stack trace/error message **
```
/home/jeff/.venv/env/lib/python3.7/site-packages/gpytorch/utils/linear_cg.py:296: UserWarning: CG terminated in 1000 iterations with average residual norm 688767.5610146187 which is larger than the tolerance of 1 specified by gpytorch.settings.cg_tolerance. If performance is affected, consider raising the maximum number of CG iterations by running code in a gpytorch.settings.max_cg_iterations(value) context.
  " a gpytorch.settings.max_cg_iterations(value) context.".format(k + 1, residual_norm.mean(), tolerance)
```

## Expected Behavior

It might be that it is training for too long and underflowing somewhere, but I am not sure as to what would cause this and the error message is quite hard to make out without knowing everything about the internal workings of the optimization process, which I am unfamiliar with. 

## System information

**Please complete the following information:**
- 0.3.5
- 1.5.1
- Mac 10.15.5

**Comment by jacobrgardner** [comment]
My guess is the lengthscale is getting very long or the likelihood noise is getting very low leading to a nearly singular matrix. Do you have a small reproducing example, or at least what UCI dataset is it? What is the final output of `print(list(model.named_parameters()))`?

For exact GPs, try training for like 50 iterations with a learning rate of 0.1.

**Comment by jeffwillette** [comment]
In my code, I was intentionally choosing an imbalanced train/test split and had a lot of extra code for doing that. In that case the lengthscale and noise parameters were `ls: 1.8237210890558038 noise: 0.004198616298847874` when the error started happening. The named parameter output after training is:

```
[('likelihood.noise_covar.raw_noise', Parameter containing:7319403012ls: 1.974623956960261 noise: 0.0020608602902027037:
tensor([-6.2334], device='cuda:0', dtype=torch.float64, requires_grad=True)), ('mean_module.constant', Parameter containing:
tensor([-4.4151], device='cuda:0', dtype=torch.float64, requires_grad=True)), ('covar_module.raw_outputscale', Parameter containing:
tensor(8.8442, device='cuda:0', dtype=torch.float64, requires_grad=True)), ('covar_module.base_kernel.raw_lengthscale', Parameter containing:
tensor([[1.8252]], device='cuda:0', dtype=torch.float64, requires_grad=True))]
```

I tried to make a reproducing example with just the raw UCI dataset (without the extra code of choosing an unbalanced split) and instead of the same error, I get a singular error from cholesky.

```
Traceback (most recent call last):
  File "gp.py", line 103, in <module>
    train()
  File "gp.py", line 90, in train
    ll = mll(yhat, y) - np.log(y_std)  # type: ignore
  File "/home/jeff/.venv/env/lib/python3.7/site-packages/gpytorch/module.py", line 22, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/jeff/.venv/env/lib/python3.7/site-packages/gpytorch/mlls/exact_marginal_log_likelihood.py", line 28, in forward
    res = output.log_prob(target)
  File "/home/jeff/.venv/env/lib/python3.7/site-packages/gpytorch/distributions/multivariate_normal.py", line 150, in log_prob
    inv_quad_rhs=diff.unsqueeze(-1), logdet=True
  File "/home/jeff/.venv/env/lib/python3.7/site-packages/gpytorch/lazy/lazy_tensor.py", line 1000, in inv_quad_logdet
    cholesky = CholLazyTensor(self.cholesky())
  File "/home/jeff/.venv/env/lib/python3.7/site-packages/gpytorch/lazy/lazy_tensor.py", line 726, in cholesky
    res = self._cholesky()
  File "/home/jeff/.venv/env/lib/python3.7/site-packages/gpytorch/utils/memoize.py", line 34, in g
    add_to_cache(self, cache_name, method(self, *args, **kwargs))
  File "/home/jeff/.venv/env/lib/python3.7/site-packages/gpytorch/lazy/lazy_tensor.py", line 403, in _cholesky
    cholesky = psd_safe_cholesky(evaluated_mat.double()).to(self.dtype)
  File "/home/jeff/.venv/env/lib/python3.7/site-packages/gpytorch/utils/cholesky.py", line 46, in psd_safe_cholesky
    raise e
  File "/home/jeff/.venv/env/lib/python3.7/site-packages/gpytorch/utils/cholesky.py", line 21, in psd_safe_cholesky
    L = torch.cholesky(A, upper=upper, out=out)
RuntimeError: cholesky_cuda: U(88,88) is zero, singular U.
```

So the difference in these errors can only come about from a specific selection of train and test splits. Your suggestion of 50 iterations with a learning rate of `0.1` solves the first CG error, but it still fails with the singular U error on my reproduction example. The reproduction code is listed below. The exact UCI dataset can be downloaded from https://github.com/yaringal/DropoutUncertaintyExps/tree/master/UCI_Datasets

```
import os
from typing import Tuple

import gpytorch  # type: ignore
import numpy as np  # type: ignore
import torch
from gpytorch.distributions import MultivariateNormal  # type: ignore
from gpytorch.likelihoods import GaussianLikelihood  # type: ignore
from gpytorch.mlls import ExactMarginalLogLikelihood  # type: ignore


def get_dataset(datadir: str) -> Tuple[torch.Tensor, ...]:
    """
    dataset can bw downloaded from here:
    https://github.com/yaringal/DropoutUncertaintyExps/tree/master/UCI_Datasets
    """
    # load data
    path = os.path.join(datadir, "UCI_Datasets", "concrete", "data", "data.txt")
    data = torch.from_numpy(np.loadtxt(path)).float()

    # make a random split of train and test
    idx_perm = torch.randperm(data.size(0))
    train_n = int(data.size(0) * 0.9)

    # extract the features and labels
    train_ft = data[idx_perm[:train_n], :-1]
    train_label = data[idx_perm[:train_n], -1]
    test_ft = data[idx_perm[train_n:], :-1]
    test_label = data[idx_perm[train_n:], -1]

    return train_ft, train_label, test_ft, test_label


class ExactGP(gpytorch.models.ExactGP):
    def __init__(
        self,
        train_x: torch.Tensor,
        train_y: torch.Tensor,
        likelihood: GaussianLikelihood,
    ) -> None:
        super(ExactGP, self).__init__(train_x, train_y, likelihood)
        self.mean_module = gpytorch.means.ConstantMean()
        self.covar_module = gpytorch.kernels.ScaleKernel(gpytorch.kernels.RBFKernel())

    def forward(self, x: torch.Tensor) -> MultivariateNormal:
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)

        return MultivariateNormal(mean_x, covar_x)


def train() -> None:
    train_x, train_y, test_x, test_y = get_dataset("/home/jeff/datasets")

    x_mu, x_std = train_x.mean(dim=0), train_x.std(dim=0)
    y_mu, y_std = train_y.mean(dim=0), train_y.std(dim=0)

    train_x = (train_x - x_mu) / x_std
    train_y = (train_y - y_mu) / y_std
    test_x = (test_x - x_mu) / x_std
    test_y = (test_y - y_mu) / y_std

    likelihood = GaussianLikelihood().double()
    model = ExactGP(train_x, train_y, likelihood).cuda().double()  # type: ignore

    mll = ExactMarginalLogLikelihood(likelihood, model)
    optimizer = torch.optim.Adam([{"params": model.parameters()}], lr=1e-2)

    print("data sizes: ", train_x.size(), train_y.size(), test_x.size(), test_y.size())

    for i in range(1000):
        model.train()
        likelihood.train()

        x, y = train_x.cuda().double(), train_y.cuda().double()

        output = model(x)
        loss = -mll(output, y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        model.eval()
        likelihood.eval()

        x, y = test_x.cuda().double(), test_y.cuda().double()

        yhat = likelihood(model(x))
        ll = mll(yhat, y) - np.log(y_std)  # type: ignore

        desc = (
            f"iter: {i} mll: {-loss.item()} test ll: {ll.item()} "
            f"ls: {model.covar_module.base_kernel.lengthscale.item()} "
            f"noise: {model.likelihood.noise.item()}"
        )
        print(desc)

    print(list(model.named_parameters()))


if __name__ == "__main__":
    train()
```

**Comment by jacobrgardner** [comment]
@jeffwillette The error is actually in computing a _joint_ test LL, which can become pretty unstable. I would recommend evaluated marginal test LLs, as this is generally the standard (e.g., when test nll is reported, it is typically marginal test nll because we don't assume access to all test data simultaneously). To do this, replace:
```diff
yhat = likelihood(model(x))
- ll = mll(yhat, y) - np.log(y_std)  # type: ignore
+ ll = torch.distributions.Normal(yhat.mean, yhat.variance.sqrt()).log_prob(y).mean()
```

**Comment by jeffwillette** [comment]
Thanks, that fixed it.

**Comment by jeffwillette** [comment]
This worked, and then I ran into into a new issue with the same model as above when I ran in on the full set of datasets. I get a negative variance from the likelihood. It seems this is a previous issue where the code is generally requested so I think we have a clear case here where everything is already specified here. https://github.com/cornellius-gp/gpytorch/issues/864

```
yhat = likelihood(model(x))
mu, sigma = yhat.mean, torch.sqrt(yhat.variance)
print(f"variance max: {yhat.variance.max()} min: {yhat.variance.min()}")
# OUTPUT: variance max: 0.18114451544687005 min: -0.008376546905163772        
```

This happens in the same datasets as above during the testing loop of the `naval-propulsion-plant` dataset.

**Comment by gpleiss** [comment]
@jeffwillette can you try wrapping this last code block with a `with gpytorch.settings.fast_pred_var():` context manager?

**Comment by jeffwillette** [comment]
@gpleiss that seems to have worked. Can you explain why that solved the problem? The [docs](https://docs.gpytorch.ai/en/v1.1.1/settings.html#gpytorch.settings.fast_pred_var) say that this estimates the variance, but I would expect a variance estimate to be more likely to produce this kind of error rather than fix it...

Shouldn't the exact calculated variance be guaranteed to be more than 0?

**Comment by gpleiss** [comment]
> Shouldn't the exact calculated variance be guaranteed to be more than 0?

In exact arithmetic, yes. However, it might be the case that the numerical errors from CG cause the variance to be negative for some reason. Since you provided us with a complete code example (thank you!!!) I'll see if I can't figure out if there's some easy bug in our normal CG variance computations .
