### ISSUE TITLE
[Docs] How to use SpectralMixtureKernel for BatchIndependent MultiOutput GP

### ISSUE THREAD

**Issue by SomeshDaga** [cornellius-gp/gpytorch#1329]
# 📚 Documentation/Examples

** Is there documentation missing? **
This is a question about a specific use case.

I'd like to use the SpectralMixtureKernel to map a common set of input data to multiple outputs, without needing to determine correlation between the different outputs. It seems this is what the `BatchIndependent` (https://docs.gpytorch.ai/en/v1.2.1/examples/03_Multitask_Exact_GPs/Batch_Independent_Multioutput_GP.html) framework is for. However, I am having a hard time getting it to output the correct dimensions for the covariance matrices i.e. the expected size of the covariance matrices obtained from passing the input data through the SpectralMixtureKernel should be `[3, 100, 100]` for the scenario described below.

As an example, I have input data of size `[100, 15]` (i.e. 100 samples and 15 dimensions) and input targets of size `[100, 3]`. I'd like effectively create 3 independent GPs (one for each target dimension) that use the same input data. From the examples in the documentation (https://docs.gpytorch.ai/en/v1.2.1/kernels.html#spectralmixturekernel), it seems like batched and non-batched data give the same output covariance of size `[100,100]` which is effectively just representing a single GP. 

** Is documentation wrong? **
No

** Is there a feature that needs some example code? **

** Think you know how to fix the docs? ** (If so, we'd love a pull request from you!)

- Link to [GPyTorch documentation](https://gpytorch.readthedocs.io)
- Link to [GPyTorch examples](https://github.com/cornellius-gp/gpytorch/tree/master/examples)

**Comment by SomeshDaga** [comment]
Here is a code snippet of what I tried

```python
import torch
import gpytorch as gp


class SpectralMixtureGP(gp.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood):
        self.train_x = train_x
        self.train_y = train_y
        super(SpectralMixtureGP, self).__init__(train_x, train_y, likelihood)
        self.mean_module = gp.means.ConstantMean(batch_shape=torch.Size([train_y.size()[-1]]))
        self.covar_module = gp.kernels.SpectralMixtureKernel(num_mixtures=4, ard_num_dims=train_x.size()[-1],
                                                             batch_shape=torch.Size([train_y.size()[-1]]))
        self.covar_module.initialize_from_data(self.train_x, self.train_y)

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        print("Mean_x size: {}, Covar_x size: {}".format(mean_x.size(), covar_x.size()))
        return gp.distributions.MultitaskMultivariateNormal.from_batch_mvn(
                gp.distributions.MultivariateNormal(mean_x, covar_x)
            )


# Define data
train_x = torch.randn(100, 15)
train_y = torch.randn(100, 3)

# Define likelihood
likelihood = gp.likelihoods.MultitaskGaussianLikelihood(num_tasks=train_y.size()[-1]).cuda()

# Initialize model
model = SpectralMixtureGP(train_x, train_y, likelihood)

# Train the model
model.train()
likelihood.train()

mll = gp.mlls.ExactMarginalLogLikelihood(likelihood, model)

# Create optimizer
optimizer = torch.optim.Adam(model.parameters(), lr=0.1)

for _ in range(100):
    optimizer.zero_grad()
    output = model(train_x)
    loss = -mll(output, train_y)
    loss.backward()
    optimizer.step()
```
The size of the mean and covariance matrices seem to be what I need, however, I get the following error. I understand that the `batch_shape` argument for the `SpectralMixtureKernel` is not following the documentation of the API where my `train_x` is of size `[100,15]` instead of `[3,100,15]`. The behavior of the the `batch_shape` argument seems to differ from that of the other standard kernels. I'm not sure how to get the intended result.

```
Traceback (most recent call last):
  File "/home/somesh/imitation/src/imitation/sandbox/test.py", line 46, in <module>
    loss = -mll(output, train_y)
  File "/home/somesh/imitation/lib/python3.7/site-packages/gpytorch/module.py", line 28, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/somesh/imitation/lib/python3.7/site-packages/gpytorch/mlls/exact_marginal_log_likelihood.py", line 62, in forward
    res = output.log_prob(target)
  File "/home/somesh/imitation/lib/python3.7/site-packages/gpytorch/distributions/multitask_multivariate_normal.py", line 202, in log_prob
    return super().log_prob(value.view(*value.shape[:-2], -1))
  File "/home/somesh/imitation/lib/python3.7/site-packages/gpytorch/distributions/multivariate_normal.py", line 140, in log_prob
    inv_quad, logdet = covar.inv_quad_logdet(inv_quad_rhs=diff.unsqueeze(-1), logdet=True)
  File "/home/somesh/imitation/lib/python3.7/site-packages/gpytorch/lazy/lazy_tensor.py", line 1022, in inv_quad_logdet
    cholesky = CholLazyTensor(TriangularLazyTensor(self.cholesky()))
  File "/home/somesh/imitation/lib/python3.7/site-packages/gpytorch/lazy/lazy_tensor.py", line 750, in cholesky
    chol = self._cholesky(upper=False)
  File "/home/somesh/imitation/lib/python3.7/site-packages/gpytorch/utils/memoize.py", line 59, in g
    return _add_to_cache(self, cache_name, method(self, *args, **kwargs), *args, kwargs_pkl=kwargs_pkl)
  File "/home/somesh/imitation/lib/python3.7/site-packages/gpytorch/lazy/lazy_tensor.py", line 407, in _cholesky
    evaluated_kern_mat = self.evaluate_kernel()
  File "/home/somesh/imitation/lib/python3.7/site-packages/gpytorch/lazy/lazy_tensor.py", line 914, in evaluate_kernel
    return self.representation_tree()(*self.representation())
  File "/home/somesh/imitation/lib/python3.7/site-packages/gpytorch/lazy/lazy_tensor.py", line 1296, in representation_tree
    return LazyTensorRepresentationTree(self)
  File "/home/somesh/imitation/lib/python3.7/site-packages/gpytorch/lazy/lazy_tensor_representation_tree.py", line 13, in __init__
    representation_size = len(arg.representation())
  File "/home/somesh/imitation/lib/python3.7/site-packages/gpytorch/lazy/lazy_tensor.py", line 1284, in representation
    representation += list(arg.representation())
  File "/home/somesh/imitation/lib/python3.7/site-packages/gpytorch/lazy/lazy_evaluated_kernel_tensor.py", line 307, in representation
    return self.evaluate_kernel().representation()
  File "/home/somesh/imitation/lib/python3.7/site-packages/gpytorch/utils/memoize.py", line 59, in g
    return _add_to_cache(self, cache_name, method(self, *args, **kwargs), *args, kwargs_pkl=kwargs_pkl)
  File "/home/somesh/imitation/lib/python3.7/site-packages/gpytorch/lazy/lazy_evaluated_kernel_tensor.py", line 274, in evaluate_kernel
    res = self.kernel(x1, x2, diag=False, last_dim_is_batch=self.last_dim_is_batch, **self.params)
  File "/home/somesh/imitation/lib/python3.7/site-packages/gpytorch/kernels/kernel.py", line 396, in __call__
    res = lazify(super(Kernel, self).__call__(x1_, x2_, last_dim_is_batch=last_dim_is_batch, **params))
  File "/home/somesh/imitation/lib/python3.7/site-packages/gpytorch/module.py", line 28, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/somesh/imitation/lib/python3.7/site-packages/gpytorch/kernels/spectral_mixture_kernel.py", line 272, in forward
    "(based on the batch_size argument). Got {}.".format(self.batch_shape, batch_shape)
RuntimeError: The SpectralMixtureKernel expected the input to have a batch_size of torch.Size([3]) (based on the batch_size argument). Got torch.Size([]).
Mean_x size: torch.Size([3, 100]), Covar_x size: torch.Size([3, 100, 100])

Process finished with exit code 1
```

**Comment by gpleiss** [comment]
Sorry for the slow reply @SomeshDaga ! It looks like the spectral mixture kernel code is a bit old and needs updating to work with broadcasting. I'm putting up a PR now to fix this.

**Comment by SomeshDaga** [comment]
@gpleiss No worries. Thanks for the update.
