### ISSUE TITLE
[Bug?]

### ISSUE THREAD

**Issue by ZhiliangWu** [cornellius-gp/gpytorch#1330]
# 🐛 Bug

`Shapes are not broadcastable for mul operation` for [`BatchDecoupledVariationalStrategy`](https://docs.gpytorch.ai/en/latest/variational.html#gpytorch.variational.BatchDecoupledVariationalStrategy) in multi-output GP. 

## To reproduce

```python
import math
import torch
import gpytorch
import tqdm
from matplotlib import pyplot as plt

train_x = torch.linspace(0, 1, 100)

train_y = torch.stack([
    torch.sin(train_x * (2 * math.pi)) + torch.randn(train_x.size()) * 0.2,
    torch.cos(train_x * (2 * math.pi)) + torch.randn(train_x.size()) * 0.2,
    torch.sin(train_x * (2 * math.pi)) + 2 * torch.cos(train_x * (2 * math.pi)) + torch.randn(train_x.size()) * 0.2,
    -torch.cos(train_x * (2 * math.pi)) + torch.randn(train_x.size()) * 0.2,
], -1)

num_latents = 3
num_tasks = 4


class IndependentMultitaskGPModel(gpytorch.models.ApproximateGP):
    def __init__(self):
        # Let's use a different set of inducing points for each task
        inducing_points = torch.rand(num_tasks, 16, 1)

        # We have to mark the CholeskyVariationalDistribution as batch
        # so that we learn a variational distribution for each task
        variational_distribution = gpytorch.variational.CholeskyVariationalDistribution(
            inducing_points.size(-2), batch_shape=torch.Size([num_tasks])
        )

        variational_strategy = gpytorch.variational.IndependentMultitaskVariationalStrategy(
            gpytorch.variational.BatchDecoupledVariationalStrategy(
                self, inducing_points, variational_distribution, learn_inducing_locations=True
            ),
            num_tasks=4, task_dim=-1
        )

        super().__init__(variational_strategy)

        # The mean and covariance modules should be marked as batch
        # so we learn a different set of hyperparameters
        self.mean_module = gpytorch.means.ConstantMean(
            batch_shape=torch.Size([num_tasks]))
        self.covar_module = gpytorch.kernels.ScaleKernel(
            gpytorch.kernels.RBFKernel(batch_shape=torch.Size([num_tasks])),
            batch_shape=torch.Size([num_tasks])
        )

    def forward(self, x):
        # The forward function should be written as if we were dealing with each output
        # dimension in batch
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)


# model = MultitaskGPModel()

model = IndependentMultitaskGPModel()
likelihood = gpytorch.likelihoods.MultitaskGaussianLikelihood(num_tasks=num_tasks)

# this is for running the notebook in our testing framework
import os
smoke_test = ('CI' in os.environ)
num_epochs = 1 if smoke_test else 500


model.train()
likelihood.train()

# We use SGD here, rather than Adam. Emperically, we find that SGD is better for variational regression
optimizer = torch.optim.Adam([
    {'params': model.hyperparameters()},
    {'params': likelihood.parameters()},
], lr=0.1)

# Our loss object. We're using the VariationalELBO, which essentially just computes the ELBO
mll = gpytorch.mlls.VariationalELBO(likelihood, model, num_data=train_y.size(0))

# We use more CG iterations here because the preconditioner introduced in the NeurIPS paper seems to be less
# effective for VI.
epochs_iter = tqdm.tqdm(range(num_epochs), desc="Epoch")
for i in epochs_iter:
    # Within each iteration, we will go over each minibatch of data
    optimizer.zero_grad()
    output = model(train_x)
    loss = -mll(output, train_y)
    epochs_iter.set_postfix(loss=loss.item())
    loss.backward()
    optimizer.step()

# Set into eval mode
model.eval()
likelihood.eval()

# Initialize plots
fig, axs = plt.subplots(1, num_tasks, figsize=(4 * num_tasks, 3))

# Make predictions
with torch.no_grad(), gpytorch.settings.fast_pred_var():
    test_x = torch.linspace(0, 1, 51)
    predictions = likelihood(model(test_x))
    mean = predictions.mean
    lower, upper = predictions.confidence_region()

for task, ax in enumerate(axs):
    # Plot training data as black stars
    ax.plot(train_x.detach().numpy(), train_y[:, task].detach().numpy(), 'k*')
    # Predictive mean as blue line
    ax.plot(test_x.numpy(), mean[:, task].numpy(), 'b')
    # Shade in confidence
    ax.fill_between(test_x.numpy(), lower[:, task].numpy(), upper[:, task].numpy(), alpha=0.5)
    ax.set_ylim([-3, 3])
    ax.legend(['Observed Data', 'Mean', 'Confidence'])
    ax.set_title(f'Task {task + 1}')

fig.tight_layout()
plt.show()
```

** Stack trace/error message **
```bash
Epoch:   0%|                                                                                                                                    | 0/500 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "multi-svgp.py", line 97, in <module>
    output = model(train_x)
  File "/home/xxxxxxxx/miniconda2/envs/xxxx/lib/python3.7/site-packages/gpytorch/models/approximate_gp.py", line 81, in __call__
    return self.variational_strategy(inputs, prior=prior)
  File "/home/xxxxxxxx/miniconda2/envs/xxxx/lib/python3.7/site-packages/gpytorch/variational/independent_multitask_variational_strategy.py", line 47, in __call__
    function_dist = self.base_variational_strategy(x, prior=prior)
  File "/home/xxxxxxxx/miniconda2/envs/xxxx/lib/python3.7/site-packages/gpytorch/variational/variational_strategy.py", line 170, in __call__
    return super().__call__(x, prior=prior)
  File "/home/xxxxxxxx/miniconda2/envs/xxxx/lib/python3.7/site-packages/gpytorch/variational/_variational_strategy.py", line 128, in __call__
    variational_inducing_covar=variational_dist_u.lazy_covariance_matrix,
  File "/home/xxxxxxxx/miniconda2/envs/xxxx/lib/python3.7/site-packages/gpytorch/module.py", line 28, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/xxxxxxxx/miniconda2/envs/xxxx/lib/python3.7/site-packages/gpytorch/variational/batch_decoupled_variational_strategy.py", line 173, in forward
    full_output = self.model.forward(full_inputs)
  File "multi-svgp.py", line 59, in forward
    mean_x = self.mean_module(x)
  File "/home/xxxxxxxx/miniconda2/envs/xxxx/lib/python3.7/site-packages/gpytorch/means/mean.py", line 22, in __call__
    res = super(Mean, self).__call__(x)
  File "/home/xxxxxxxx/miniconda2/envs/xxxx/lib/python3.7/site-packages/gpytorch/module.py", line 28, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/xxxxxxxx/miniconda2/envs/xxxx/lib/python3.7/site-packages/gpytorch/means/constant_mean.py", line 21, in forward
    return self.constant.expand(_mul_broadcast_shape(input.shape[:-1], self.constant.shape))
  File "/home/xxxxxxxx/miniconda2/envs/xxxx/lib/python3.7/site-packages/gpytorch/utils/broadcasting.py", line 20, in _mul_broadcast_shape
    raise RuntimeError("Shapes are not broadcastable for mul operation")
RuntimeError: Shapes are not broadcastable for mul operation

```

## Expected Behavior

Similar output if we replace `gpytorch.variational.VariationalStrategy` with `gpytorch.variational.VariationalStrategy` as in the [tutorial notebook](https://docs.gpytorch.ai/en/latest/examples/04_Variational_and_Approximate_GPs/SVGP_Multitask_GP_Regression.html#Train-the-model).

## System information

**Please complete the following information:**
- 1.2.1
- 1.6.0
- Debian 10

## Additional context
Actually, I am not sure whether it is a bug or feature that I haven't understood yet. The bug will disappear if I specify the `batch_shape` of mean and covariance modules as `[num_tasks, 1]` instead of `[num_tasks]`. Concretely speaking, I set

```python
        self.mean_module = gpytorch.means.ConstantMean(
            batch_shape=torch.Size([num_tasks, 1]))
        self.covar_module = gpytorch.kernels.ScaleKernel(
            gpytorch.kernels.RBFKernel(batch_shape=torch.Size([num_tasks, 1])),
            batch_shape=torch.Size([num_tasks, 1])
        )
```
However, since by default we have `task_dim=-1` in `gpytorch.variational.IndependentMultitaskVariationalStrategy`, such setting seems to be wrong as it would refer to `1`. To make the mapping correct, setting `task_dim=-2` is appealing. However, this would cause another new error message like `ValueError: only one element tensors can be converted to Python scalars`. Some clarification of how to use `BatchDecoupledVariationalStrategy` in multi-output GP, especially the setting of `batch_shape` would really be helpful.

**Comment by gpleiss** [comment]
The issue is that the mean_module and kernel_module need batch shapes that account for the decoupled mean/var batch dimension. If you change the shape to be:

```python
        self.mean_module = gpytorch.means.ConstantMean(
            batch_shape=torch.Size([num_tasks, 2]))
        self.covar_module = gpytorch.kernels.ScaleKernel(
            gpytorch.kernels.RBFKernel(batch_shape=torch.Size([num_tasks])),
            batch_shape=torch.Size([num_tasks, 2])
        )
```,

then it will work.

**Comment by gpleiss** [comment]
The updated docs now have a proper example for this.
