### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by monabf** [cornellius-gp/gpytorch#1376]
# 🐛 Bug

Sorry to bother you again, but my problem #1349 is still not solved and I cannot reopen the issue.

I installed the newest version of GPyTorch, which contains PR #1356:
`pip install --upgrade git+https://github.com/cornellius-gp/gpytorch.git`

Now running my previous example code, I get an error in the forward function. This error comes from function `chol_cap_mat` in class `LowRankRootAddedDiagLazyTensor`. I fixed the bug by using 
```python
batch_shape = torch.Size([V.batch_shape[0], 1])        
C = ConstantDiagLazyTensor(
            torch.ones(batch_shape, device=V.device, dtype=V.dtype),
            V.shape[-2])
```
instead of 
```python
C = ConstantDiagLazyTensor(torch.ones(V.batch_shape,
        device=V.device, dtype=V.dtype), V.shape[-2])
```
but this is hacky. Even with this fix, the code runs but not much faster than before.

In PR #1356, @jacobrgardner said that this fixed my problem and that my example code now had prediction times aligned with GPy. This is not the case at all for me: I get an error, and even if I don't the code is still roughly as slow. Am I not using this PR correctly? Or was there a mistake in it maybe?

Thanks a lot for your help...

## To reproduce: previous example code

```python
import time
import urllib.request
from math import floor

import GPy
import gpytorch
import torch
from gpytorch.distributions import MultivariateNormal
from gpytorch.kernels import ScaleKernel, RBFKernel, InducingPointKernel
from gpytorch.means import ConstantMean
from scipy.io import loadmat

if __name__ == '__main__':
    # Run GPyTorch SGPR + independent multioutputs example
    # https://docs.gpytorch.ai/en/v1.2.1/examples/02_Scalable_Exact_GPs/SGPR_Regression_CUDA.html
    # https://github.com/cornellius-gp/gpytorch/issues/1043
    print('Downloading \'elevators\' UCI dataset...')
    urllib.request.urlretrieve(
        'https://drive.google.com/uc?export=download&id=1jhWL3YUHvXIaftia4qeAyDwVxo6j1alk',
        '../elevators.mat')
    output_size = 2
    data = torch.Tensor(loadmat('../elevators.mat')['data'])
    X = data[:, :-1]
    X = X - X.min(0)[0]
    X = 2 * (X / X.max(0)[0]) - 1
    y = data[:, -1]
    # MAKE MULTIOUTPUT DATA
    y = y.reshape(-1, 1)
    y = y.repeat(1, output_size)
    print(X.shape, y.shape)
    train_n = int(floor(0.8 * len(X)))
    train_x = X[:train_n, :].contiguous()
    train_y = y[:train_n].contiguous()
    test_x = X[train_n:, :].contiguous()
    test_y = y[train_n:].contiguous()
    if torch.cuda.is_available():
        train_x, train_y, test_x, test_y = train_x.cuda(), train_y.cuda(), test_x.cuda(), test_y.cuda()
    # CONVERT TO BATCH GP
    train_x = train_x.repeat(output_size, 1, 1)
    train_y = train_y.transpose(-2, -1)
    test_x = test_x.repeat(output_size, 1, 1)
    test_y = test_y.transpose(-2, -1)
    print(train_x.shape, train_y.shape, test_x.shape)


    class GPRegressionModel(gpytorch.models.ExactGP):
        def __init__(self, train_x, train_y, likelihood):
            super(GPRegressionModel, self).__init__(train_x, train_y,
                                                    likelihood)
            self.mean_module = ConstantMean(
                batch_shape=torch.Size([output_size]))
            self.base_covar_module = ScaleKernel(RBFKernel(
                batch_shape=torch.Size([output_size])),
                batch_shape=torch.Size([output_size]))
            self.covar_module = InducingPointKernel(
                self.base_covar_module,
                inducing_points=train_x[:, :500, :],
                likelihood=likelihood)

        def forward(self, x):
            mean_x = self.mean_module(x)
            covar_x = self.covar_module(x)
            return MultivariateNormal(mean_x, covar_x)


    likelihood = gpytorch.likelihoods.GaussianLikelihood(
        batch_shape=torch.Size([output_size]))
    model = GPRegressionModel(train_x, train_y, likelihood)
    if torch.cuda.is_available():
        model = model.cuda()
        likelihood = likelihood.cuda()
    # Train
    training_iterations = 50
    model.train()
    likelihood.train()
    optimizer = torch.optim.SGD(model.parameters(), lr=0.1)
    mll = gpytorch.mlls.ExactMarginalLogLikelihood(likelihood, model)
    start_whole = time.time()
    for i in range(training_iterations):
        start = time.time()
        # Zero backprop gradients
        optimizer.zero_grad()
        # Get output from model
        output = model(train_x)
        # Calc loss and backprop derivatives
        loss = -mll(output, train_y).sum()
        loss.backward()
        end = time.time()
        print('Iter %d/%d - Loss: %.3f' % (
            i + 1, training_iterations, loss.item()), 'in', str(end - start))
        optimizer.step()
        torch.cuda.empty_cache()
    end_whole = time.time()
    print('GPyTorch training time', str(end_whole - start_whole))
    model.eval()
    likelihood.eval()
    start = time.time()
    with gpytorch.settings.max_preconditioner_size(10), torch.no_grad():
        with gpytorch.settings.max_root_decomposition_size(
                30), gpytorch.settings.fast_pred_var():
            preds = model(test_x)
    end = time.time()
    print('predict', str(test_x.shape[1]), 'in', str(end - start))
    print('Test MAE: {}'.format(torch.mean(torch.abs(preds.mean - test_y))))

    # Compare GPy
    train_x = X[:train_n, :].contiguous()
    train_y = y[:train_n].contiguous()
    test_x = X[train_n:, :].contiguous()
    test_y = y[train_n:].contiguous()
    gpykernel = GPy.kern.RBF(input_dim=train_x.numpy().shape[1], ARD=True)
    gpymodel = GPy.core.SparseGP(train_x.numpy(),
                                 train_y.numpy(),
                                 train_x.numpy()[:500, :],
                                 kernel=gpykernel,
                                 likelihood=GPy.likelihoods.Gaussian(),
                                 inference_method=GPy.inference.latent_function_inference.VarDTC())
    start = time.time()
    gpymodel.optimize(messages=True, max_iters=50)
    end = time.time()
    print('GPy training time', str(end - start))
    start = time.time()
    gpymean, gpyvar = gpymodel.predict(test_x.numpy())
    end = time.time()
    print('predict', str(len(test_x)), 'in', str(end - start))
    print('Test MAE: {}'.format(torch.mean(torch.abs(torch.tensor(gpymean) -
                                                     test_y))))
```

** Error message without the hacky fix **
```
Traceback (most recent call last):
  File "issue.py", line 87, in <module>
    loss = -mll(output, train_y).sum()
  File "/Users/mona/PhD_code/observer_add_GPyTorch/venv/lib/python3.8/site-packages/gpytorch/module.py", line 28, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/Users/mona/PhD_code/observer_add_GPyTorch/venv/lib/python3.8/site-packages/gpytorch/mlls/exact_marginal_log_likelihood.py", line 62, in forward
    res = output.log_prob(target)
  File "/Users/mona/PhD_code/observer_add_GPyTorch/venv/lib/python3.8/site-packages/gpytorch/distributions/multivariate_normal.py", line 141, in log_prob
    inv_quad, logdet = covar.inv_quad_logdet(inv_quad_rhs=diff.unsqueeze(-1), logdet=True)
  File "/Users/mona/PhD_code/observer_add_GPyTorch/venv/lib/python3.8/site-packages/gpytorch/lazy/low_rank_root_added_diag_lazy_tensor.py", line 98, in inv_quad_logdet
    self_inv_rhs = self._solve(inv_quad_rhs)
  File "/Users/mona/PhD_code/observer_add_GPyTorch/venv/lib/python3.8/site-packages/gpytorch/lazy/low_rank_root_added_diag_lazy_tensor.py", line 42, in _solve
    chol_cap_mat = self.chol_cap_mat
  File "/Users/mona/PhD_code/observer_add_GPyTorch/venv/lib/python3.8/site-packages/gpytorch/utils/memoize.py", line 59, in g
    return _add_to_cache(self, cache_name, method(self, *args, **kwargs), *args, kwargs_pkl=kwargs_pkl)
  File "/Users/mona/PhD_code/observer_add_GPyTorch/venv/lib/python3.8/site-packages/gpytorch/lazy/low_rank_root_added_diag_lazy_tensor.py", line 31, in chol_cap_mat
    C = ConstantDiagLazyTensor(torch.ones(V.batch_shape, device=V.device, dtype=V.dtype), V.shape[-2])
  File "/Users/mona/PhD_code/observer_add_GPyTorch/venv/lib/python3.8/site-packages/gpytorch/lazy/diag_lazy_tensor.py", line 221, in __init__
    self._diag = diag_values.expand(*diag_values.shape[:-1], diag_shape)
RuntimeError: The expanded size of the tensor (500) must match the existing size (2) at non-singleton dimension 0.  Target sizes: [500].  Tensor sizes: [2]
```

** Computation time on my laptop's CPU with the hacky fix **
```
GPyTorch training time 113.91816210746765
predict 3320 in 3.4245238304138184
Test MAE: 0.07138565927743912

GPy training time 331.20656394958496
predict 3320 in 0.10564208030700684
Test MAE: 0.06792577020335427
```

## Expected Behavior

I expected no error and roughly equal prediction times.

## System information

- GPyTorch version 1.2.0
- PyTorch version 1.6.0
- Mac OS Catalina

**Comment by jacobrgardner** [comment]
It's possible something broke from code review changes. I'll take a look

**Comment by monabf** [comment]
Great, thanks a lot!

**Comment by monabf** [comment]
Hi, sorry to bother you again, but are there any news on this? Thanks a lot!

**Comment by jacobrgardner** [comment]
Hi @monabf --

Hi @monabf --

Best I can tell what's going on here, this might just be a matter of timing difference between the two packages about when certain test time caches are computed. In GPyTorch, we'll end up computing a bunch of caches (e.g., `K_uu, `chol(K_uu)`, a cache for the mean and variance), but only the first time you call predict again.

Even on the CPU, the second and subsequent times I call predict it takes 93 ms, down from 2.5 seconds.

The PR did result in a substantial speed improvement on the GPU. On a commit before my PR, I get:
```
GPyTorch training time 10.187169075012207
predict 3320 in 0.17602753639221191
```
while on master I get:
```
GPyTorch training time 3.348576307296753
predict 3320 in 0.10800027847290039
```

**Comment by monabf** [comment]
Hi @jacobrgardner, thanks for the quick reply and for fixing the bug! That was my main issue, I'm happy to see the example code now runs as expected.

Concerning the speed, you're probably right: GPy might compute the caches during training rather than on the first predict. 
However, the prediction time difference between both is still unexpected: the GPyTorch training + 1st prediction time aligns with GPy training time (roughly), but not for the second prediction, most of all in higher dimensions. If I change my code to output_size = 5, I obtain:

```
GPyTorch training time 75.94022297859192
predict 3320 in 9.342249870300293
predict 2nd time 3320 in 1.103367805480957

GPy training time 103.96773028373718
predict 3320 in 0.1411118507385254
predict 2nd time 3320 in 0.1654059886932373
```

And with 1000 inducing points instead of 500:

```
GPyTorch training time 198.27304410934448
predict 3320 in 30.224947929382324
predict 2nd time 3320 in 8.705496072769165

GPy training time 233.62045001983643
predict 3320 in 0.2862741947174072
predict 2nd time 3320 in 0.28592777252197266
```

On my original use case (20,000x7 inputs, 20,000x5 outputs, 500 inducing points), each prediction still takes around 1s with GPyTorch on CPU, against 1ms with GPy. I guess for most use cases it is fine if training takes a long time, that's part of the process, but usually we expect prediction to be fast so that the trained model can easily be used. Here I need hours to predict my 20,000 test inputs. 

Single prediction time was closer to 10s than to 1s before the PR, so it definitely brought some improvement, but it is still not fast enough to predict long trajectories with multi-output datasets. I don't know how you guys usually do that, should I be using some other method instead of SGPR? 

Thanks a lot for your help...
