### ISSUE TITLE
Create .exe from gypytorch models

### ISSUE THREAD

**Issue by ml1991** [cornellius-gp/gpytorch#1379]
Hi,

I am trying to create a standalone executable from my gpytorch models. I am using pyinstaller for this. 
When I try to run the executable I get the following error:

Traceback (most recent call last):
  File "site-packages\torch\_utils_internal.py", line 46, in get_source_lines_and_file
  File "inspect.py", line 955, in getsourcelines
  File "inspect.py", line 786, in findsource
OSError: could not get source code

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gpExample.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\user\.conda\envs\exe2\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\gpytorch\__init__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\user\.conda\envs\exe2\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\gpytorch\distributions\__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\user\.conda\envs\exe2\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\gpytorch\distributions\delta.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\user\.conda\envs\exe2\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\gpytorch\distributions\multivariate_normal.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\user\.conda\envs\exe2\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\gpytorch\lazy\__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\user\.conda\envs\exe2\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\gpytorch\lazy\added_diag_lazy_tensor.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\user\.conda\envs\exe2\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\gpytorch\utils\__init__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\user\.conda\envs\exe2\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\gpytorch\utils\linear_cg.py", line 15, in <module>
  File "site-packages\torch\jit\__init__.py", line 1278, in script
  File "site-packages\torch\jit\frontend.py", line 162, in get_jit_def
  File "site-packages\torch\_utils_internal.py", line 50, in get_source_lines_and_file
OSError: Can't get source for site-packages\gpytorch\utils\linear_cg.py. TorchScript requires source access in order to carry out compilation. Make sure original .py files are available. Original error: could not get source code
[18080] Failed to execute script gpExample

Does anyone know what to do about this? I have read that pytorch isn't very compatible with pyinstaller. However, I manage to make a small example work, that imported and used pytorch. But when I try to run a small gpytorch example I get the error.

I am using:
Python 3.7.7
Pytorch 1.4.0
Gpytorch 1.0.0

Thanks!

**Comment by Balandat** [comment]
This looks very much like an issue with the pytorch JIT, I've seen this in other contexts. Basically, the runtime is not aware of the code that the JIT generates on during execution, you need to find some way of letting your packaging tool know that this is expected (I have no idea how to do that with pyinstaller on windows though). 

I'm pretty confident this is unrelated to GPyTorch and a general issue with the pytorch JIT, can you try a minimal pytorch example using the jit and see whether you run into the same issues?

**Comment by ml1991** [comment]
Thanks for the reply. You were right. I tried another example using jit and it didn't work either. If I disable jit by setting: 
os.environ["PYTORCH_JIT"] = "0"

it works.
