### ISSUE TITLE
[Docs] InducingPointKernel and Derivatives information

### ISSUE THREAD

**Issue by FuhgJan** [cornellius-gp/gpytorch#1388]
# 📚 Documentation/Examples
Hi everyone,
I am not experienced enough to judge if this is a bug or my own fault. So here we are. 
I tried to combine the code for sparse GPs and derivatives for the 1D derivative example that was provided. Both codes are running individually. 
Is there any sample code available when running an InducingPointKernel with derivative information. I am running into dimension issues in the added_loss_term of the approximate marginal.

```python
import torch
import gpytorch
import math
from matplotlib import pyplot as plt
import numpy as np

lb, ub = 0.0, 5*math.pi
n = 50

train_x = torch.linspace(lb, ub, n).unsqueeze(-1)
train_y = torch.stack([
    torch.sin(2*train_x) + torch.cos(train_x),
    -torch.sin(train_x) + 2*torch.cos(2*train_x)
], -1).squeeze(1)

train_y += 0.05 * torch.randn(n, 2)

class GPModelWithDerivatives(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood):
        super(GPModelWithDerivatives, self).__init__(train_x, train_y, likelihood)
        self.mean_module = gpytorch.means.ConstantMeanGrad()
        self.base_kernel = gpytorch.kernels.RBFKernelGrad()
        self.base_covar_module = gpytorch.kernels.ScaleKernel(self.base_kernel)
        self.covar_module = gpytorch.kernels.InducingPointKernel(self.base_covar_module, inducing_points=train_x[1:train_x.shape[0]:2,:], likelihood=likelihood)

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultitaskMultivariateNormal(mean_x, covar_x)




likelihood = gpytorch.likelihoods.MultitaskGaussianLikelihood(num_tasks=2)  # Value + Derivative
model = GPModelWithDerivatives(train_x, train_y, likelihood)

# this is for running the notebook in our testing framework
training_iter = 50


# Find optimal model hyperparameters
model.train()
likelihood.train()

# Use the adam optimizer
optimizer = torch.optim.Adam([
    {'params': model.parameters()},  # Includes GaussianLikelihood parameters
], lr=0.1)

# "Loss" for GPs - the marginal log likelihood
mll = gpytorch.mlls.ExactMarginalLogLikelihood(likelihood, model)

for i in range(training_iter):
    optimizer.zero_grad()
    output = model(train_x)
    loss = -mll(output, train_y)
    loss.backward()
    print('Iter %d/%d - Loss: %.3f' % (i + 1, training_iter, loss.item()))
    optimizer.step()
```

** Here is my stacktrace**
The noise_diag is a size 200 vector while the diag vector is dimension 100.

```
Traceback (most recent call last):
  File ".../sparse_derivate.py", line 56, in <module>
    loss = -mll(output, train_y)
  File ".../python3.8/site-packages/gpytorch/module.py", line 28, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File ".../python3.8/site-packages/gpytorch/mlls/exact_marginal_log_likelihood.py", line 63, in forward
    res = self._add_other_terms(res, params)
  File ".../python3.8/site-packages/gpytorch/mlls/exact_marginal_log_likelihood.py", line 39, in _add_other_terms
    res = res.add(added_loss_term.loss(*params))
  File ".../python3.8/site-packages/gpytorch/mlls/inducing_point_kernel_added_loss_term.py", line 20, in loss
    return 0.5 * (diag / noise_diag).sum()
RuntimeError: The size of tensor a (100) must match the size of tensor b (200) at non-singleton dimension 0

Process finished with exit code 1

```
Any help would be much appreciated.

**Comment by gpleiss** [comment]
Derivative kernels are not compatible with scalable methods like `InducingPointKernel`.

**Comment by gpleiss** [comment]
Related to #1353
