### ISSUE TITLE
[Bug] Conda dependencies allow to downgrade to Python 1.4 without complain

### ISSUE THREAD

**Issue by bsolino** [cornellius-gp/gpytorch#1524]
# 🐛 Bug

NOTE: I'm currently trying to used code that uses gpytorch, so 

I installed gpytorch with conda. I first installed cudatoolkit version 10.2, but I had to downgrade to 10.0. I currently have installed:

* gpytorch=1.4.0=pyhd8ed1ab_0
* pytorch=1.4.0=py3.8_cuda10.0.130_cudnn7.6.3_0
* cudatoolkit=10.0.130=0
* python=3.8.8=hdb3f193_4

When I downgraded, I noticed that gpytorch was not one of the packages downgraded:
```
The following packages will be DOWNGRADED:

  cudatoolkit                            10.2.89-hfd86e86_1 --> 10.0.130-0
  pytorch              1.7.1-py3.8_cuda10.2.89_cudnn7.6.5_0 --> 1.4.0-py3.8_cuda10.0.130_cudnn7.6.3_0
  torchaudio                                     0.7.2-py38 --> 0.4.0-py38
  torchvision                              0.8.2-py38_cu102 --> 0.5.0-py38_cu100
```

My intuition is that the dependencies are not well defined in conda, and that  the gpytorch package should have either be downgraded or produce an error in the environment solver.

## To reproduce

```
conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch
conda install gpytorch
conda install cudatoolkit=10.0 -c pytorch
```
Note: That's a simplified recollection of how I created the environment, details of order or channels may be different.

** Code snippet to reproduce **
```python
# Your code goes here
# Please make sure it does not require any external dependencies (other than PyTorch!)
# (We much prefer small snippets rather than links to existing libraries!)
import gpytorch
```

** Stack trace/error message **
```
Python 3.8.8 (default, Feb 24 2021, 21:46:12)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gpytorch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/miniconda3/envs/torch/lib/python3.8/site-packages/gpytorch/__init__.py", line 2, in <module>
    from . import (
  File "/miniconda3/envs/torch/lib/python3.8/site-packages/gpytorch/distributions/__init__.py", line 3, in <module>
    from .delta import Delta
  File "/miniconda3/envs/torch/lib/python3.8/site-packages/gpytorch/distributions/delta.py", line 10, in <module>
    from .multivariate_normal import MultivariateNormal
  File "/miniconda3/envs/torch/lib/python3.8/site-packages/gpytorch/distributions/multivariate_normal.py", line 12, in <module>
    from ..lazy import DiagLazyTensor, LazyTensor, RootLazyTensor, delazify, lazify
  File "/miniconda3/envs/torch/lib/python3.8/site-packages/gpytorch/lazy/__init__.py", line 32, in <module>
    from .toeplitz_lazy_tensor import ToeplitzLazyTensor
  File "/miniconda3/envs/torch/lib/python3.8/site-packages/gpytorch/lazy/toeplitz_lazy_tensor.py", line 5, in <module>
    from ..utils.toeplitz import sym_toeplitz_derivative_quadratic_form, sym_toeplitz_matmul
  File "/miniconda3/envs/torch/lib/python3.8/site-packages/gpytorch/utils/toeplitz.py", line 4, in <module>
    from torch.fft import fft, ifft
ModuleNotFoundError: No module named 'torch.fft'
```

## Expected Behavior

I've noticed that the installation instructions mention "GPyTorch requires Python >= 3.6 and PyTorch >= 1.6". I shouldn't have been able to install gpytorch, or conda should have installed a version that was compatible.

## System information

**Please complete the following information:**
- 1.4.0
-  1.4.0
-  Red Hat 4.4.7-23

**Comment by gpleiss** [comment]
I'm not really sure what's going on here. Let's see if it's fixed on the next release.

**Comment by MJimitater** [comment]
same issue here
