### ISSUE TITLE
[Bug] Inf value calculated by mll 

### ISSUE THREAD

**Issue by Luckick** [cornellius-gp/gpytorch#1579]
# 🐛 Bug

## To reproduce

** Code snippet to reproduce **
```python
import gpytorch
from gpytorch.models import ApproximateGP
from gpytorch.likelihoods import BetaLikelihood
from gpytorch.variational import VariationalStrategy
from gpytorch.variational import NaturalVariationalDistribution
from gpytorch.priors import SmoothedBoxPrior
from gpytorch.distributions import base_distributions
import torch
from gpytorch.models import ExactGP
from gpytorch.kernels import MaternKernel, ScaleKernel
from gpytorch.means import ConstantMean
from  gpytorch.distributions import MultivariateNormal

class base_model(ApproximateGP):
  def __init__(self, train_x):
    distribution = CholeskyVariationalDistribution(train_x.shape[0])
    variational_strategy = VariationalStrategy(self, train_x, distribution, learn_inducing_locations=True)
    super(base_model, self).__init__(variational_strategy)
    self.mean_module = gpytorch.means.ConstantMean(prior=SmoothedBoxPrior(0.5, 1))
    num_dims = len(train_x) if len(train_x) == 0 else len(train_x[0])
    kernel = MaternKernel(nu=2.5, ard_num_dims=num_dims)
    self.covar_module = ScaleKernel(kernel)

  def forward(self, x):
    mean_x = self.mean_module(x)
    covar_x = self.covar_module(x)
    latent_pred = gpytorch.distributions.MultivariateNormal(mean_x, covar_x)
    return latent_pred

class BetaGP_Model:
  def __init__(self, X, y, training_iters=100, learning_rate=0.1,  gpu=False, nu=2.5,n_restarts=0):
    self.X = X
    self.y = y
    self.training_iters = training_iters
    self.learning_rate = learning_rate
    self.gpu = gpu
    self.n_restarts = n_restarts
    self.likelihood = BetaLikelihood()
    self.model = base_model(self.X)
    if torch.cuda.is_available() and gpu == True:
      self.model = self.model.cuda()

  def fit(self):
    self.model.train()
    self.likelihood.train()
    optimizer = torch.optim.Adam([{'params': self.model.parameters()}, ], lr=self.learning_rate)
    mll = gpytorch.mlls.VariationalELBO(self.likelihood, self.model, num_data=y.size(0))
    for restart in range(0 + 1):
      for i in range(self.training_iters):
        optimizer.zero_grad()
        output = self.model(self.X)
        loss = -mll(output, self.y)
        loss.backward()
        optimizer.step()

model = BetaGP_Model(X, y, training_iters=100, learning_rate=0.1, gpu=False, nu=2.5, n_restarts=0)
model.fit()
```

** Stack trace/error message **
The loss will be inf after 1st iteration, then after backpropagation, the covariance will be nan values. 

```
Traceback (most recent call last):
  File "/home/qil15006/.conda/envs/edbo/lib/python3.7/site-packages/gpytorch/utils/cholesky.py", line 32, in psd_safe_cholesky
    L = torch.cholesky(A, upper=upper, out=out)
RuntimeError: cholesky_cpu: U(1,1) is zero, singular U.

Traceback (most recent call last):
  File "/home/qil15006/tmp/pycharm_project_623/experiments/simplified.py", line 77, in <module>
    model.fit()
  File "/home/qil15006/tmp/pycharm_project_623/experiments/simplified.py", line 65, in fit
    output = self.model(self.X)
  File "/home/qil15006/.conda/envs/edbo/lib/python3.7/site-packages/gpytorch/models/approximate_gp.py", line 81, in __call__
    return self.variational_strategy(inputs, prior=prior, **kwargs)
  File "/home/qil15006/.conda/envs/edbo/lib/python3.7/site-packages/gpytorch/variational/variational_strategy.py", line 168, in __call__
    return super().__call__(x, prior=prior, **kwargs)
  File "/home/qil15006/.conda/envs/edbo/lib/python3.7/site-packages/gpytorch/variational/_variational_strategy.py", line 129, in __call__
    **kwargs,
  File "/home/qil15006/.conda/envs/edbo/lib/python3.7/site-packages/gpytorch/module.py", line 28, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/qil15006/.conda/envs/edbo/lib/python3.7/site-packages/gpytorch/variational/variational_strategy.py", line 103, in forward
    L = self._cholesky_factor(induc_induc_covar)
  File "/home/qil15006/.conda/envs/edbo/lib/python3.7/site-packages/gpytorch/utils/memoize.py", line 76, in g
    return _add_to_cache_ignore_args(self, cache_name, method(self, *args, **kwargs))
  File "/home/qil15006/.conda/envs/edbo/lib/python3.7/site-packages/gpytorch/variational/variational_strategy.py", line 72, in _cholesky_factor
    L = psd_safe_cholesky(delazify(induc_induc_covar).double())
  File "/home/qil15006/.conda/envs/edbo/lib/python3.7/site-packages/gpytorch/utils/cholesky.py", line 38, in psd_safe_cholesky
    f"cholesky_cpu: {isnan.sum().item()} of {A.numel()} elements of the {A.shape} tensor are NaN."
gpytorch.utils.errors.NanError: cholesky_cpu: 10000 of 10000 elements of the torch.Size([100, 100]) tensor are NaN.
```

## Expected Behavior
Non Inf value

## System information

**Please complete the following information:**
GPyTorch Version (`1.4.0`)
PyTorch Version (`1.8.1+cu102`) 
Computer OS  Ubuntu 16.04.7

**Comment by Luckick** [comment]
It turns out the y should not be exactly 0 nor 1. 
We can add a small perturbation and the problem is solved.
