### ISSUE TITLE
[Docs] cannot open elevator.mat with scipy's loadmat

### ISSUE THREAD

**Issue by ziatdinovmax** [cornellius-gp/gpytorch#1636]
In the '06_PyTorch_NN_Integration_DKL' notebook, it gives the following error:
```
ValueError: Unknown mat file type, version 108, 59
```
I currently use scipy 1.4.1 but even upgrading to 1.6.3 did not solve the issue. Unfortunately, I don't have an access to Matlab to check the file, while the Octave also throws an error when trying to open it. Would you mind looking into this?

Thanks in advance!

**Comment by FrankCold** [comment]
I have exactly the same problem.

`Traceback (most recent call last):

  File "<ipython-input-35-7468a3771e29>", line 1, in <module>
    data = torch.Tensor(loadmat('elevators.mat')['data'])

  File "C:\Users\Francisco Caldas\anaconda3\lib\site-packages\scipy\io\matlab\mio.py", line 225, in loadmat
    MR, _ = mat_reader_factory(f, **kwargs)

  File "C:\Users\Francisco Caldas\anaconda3\lib\site-packages\scipy\io\matlab\mio.py", line 74, in mat_reader_factory
    mjv, mnv = get_matfile_version(byte_stream)

  File "C:\Users\Francisco Caldas\anaconda3\lib\site-packages\scipy\io\matlab\miobase.py", line 231, in get_matfile_version
    raise ValueError('Unknown mat file type, version %s, %s' % ret)

ValueError: Unknown mat file type, version 108, 59`

**Comment by gpleiss** [comment]
This is weird. I'm taking a look right now

**Comment by gpleiss** [comment]
It looks like the file on the server may have been corrupted. @jacobrgardner can you check the file?
In the meantime, I've attached the dataset so that you can run the notebook.


[elevators.mat.zip](https://github.com/cornellius-gp/gpytorch/files/6625605/elevators.mat.zip)

**Comment by ziatdinovmax** [comment]
@gpleiss thank you!
