### ISSUE TITLE
[Bug] `python setup.py test` fails

### ISSUE THREAD

**Issue by samuela** [cornellius-gp/gpytorch#1736]
# 🐛 Bug

The setuptools tests are broken. I discovered this while packaging for Nix, but presumably the same failure could be seen via `python setup.py test`.

## To reproduce
I'm building via Nix, but everything should be the same without Nix as well. Here's my full derivation:
```nix
{ buildPythonPackage, fetchPypi, lib
, pytorch, scikit-learn
}:

buildPythonPackage rec {
  pname = "gpytorch";
  version = "1.5.0";

  src = fetchPypi {
    inherit pname version;
    sha256 = "sha256:0xijni7pavyv5hx42qcnglp3l0mbdz719jv4pm7a0cfk6fhr6hag";
  };

  # pip dependencies
  propagatedBuildInputs = [ pytorch scikit-learn ];

  pythonImportsCheck = [ "gpytorch" ];

  meta = with lib; {
    description = "An implementation of Gaussian Processes in Pytorch";
    homepage    = "https://gpytorch.ai/";
    license     = licenses.mit;
    maintainers = with maintainers; [ samuela ];
  };
}
```

** Stack trace/error message **
```
setuptoolsCheckPhase
Executing setuptoolsCheckPhase
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
writing gpytorch.egg-info/PKG-INFO
writing dependency_links to gpytorch.egg-info/dependency_links.txt
writing requirements to gpytorch.egg-info/requires.txt
writing top-level names to gpytorch.egg-info/top_level.txt
reading manifest file 'gpytorch.egg-info/SOURCES.txt'
writing manifest file 'gpytorch.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "/build/gpytorch-1.5.0/nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 41, in <module>
    setup(
  File "/nix/store/cr08vgmnr3qvdxmrifshnv0xd336w0ah-python3.9-setuptools-57.2.0/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/nix/store/nki9ywqzbvz68vr75kn2r7g1q84f5agy-python3-3.9.6/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/nix/store/nki9ywqzbvz68vr75kn2r7g1q84f5agy-python3-3.9.6/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/nix/store/nki9ywqzbvz68vr75kn2r7g1q84f5agy-python3-3.9.6/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/nix/store/cr08vgmnr3qvdxmrifshnv0xd336w0ah-python3.9-setuptools-57.2.0/lib/python3.9/site-packages/setuptools/command/test.py", line 232, in run
    self.run_tests()
  File "/nix/store/cr08vgmnr3qvdxmrifshnv0xd336w0ah-python3.9-setuptools-57.2.0/lib/python3.9/site-packages/setuptools/command/test.py", line 250, in run_tests
    test = unittest.main(
  File "/nix/store/nki9ywqzbvz68vr75kn2r7g1q84f5agy-python3-3.9.6/lib/python3.9/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/nix/store/nki9ywqzbvz68vr75kn2r7g1q84f5agy-python3-3.9.6/lib/python3.9/unittest/main.py", line 124, in parseArgs
    self._do_discovery(argv[2:])
  File "/nix/store/nki9ywqzbvz68vr75kn2r7g1q84f5agy-python3-3.9.6/lib/python3.9/unittest/main.py", line 244, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File "/nix/store/nki9ywqzbvz68vr75kn2r7g1q84f5agy-python3-3.9.6/lib/python3.9/unittest/main.py", line 154, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/nix/store/nki9ywqzbvz68vr75kn2r7g1q84f5agy-python3-3.9.6/lib/python3.9/unittest/loader.py", line 349, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/nix/store/nki9ywqzbvz68vr75kn2r7g1q84f5agy-python3-3.9.6/lib/python3.9/unittest/loader.py", line 405, in _find_tests
    tests, should_recurse = self._find_test_path(
  File "/nix/store/nki9ywqzbvz68vr75kn2r7g1q84f5agy-python3-3.9.6/lib/python3.9/unittest/loader.py", line 483, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/nix/store/cr08vgmnr3qvdxmrifshnv0xd336w0ah-python3.9-setuptools-57.2.0/lib/python3.9/site-packages/setuptools/command/test.py", line 50, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/nix/store/nki9ywqzbvz68vr75kn2r7g1q84f5agy-python3-3.9.6/lib/python3.9/unittest/loader.py", line 191, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/nix/store/cr08vgmnr3qvdxmrifshnv0xd336w0ah-python3.9-setuptools-57.2.0/lib/python3.9/site-packages/setuptools/command/test.py", line 50, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/nix/store/nki9ywqzbvz68vr75kn2r7g1q84f5agy-python3-3.9.6/lib/python3.9/unittest/loader.py", line 205, in loadTestsFromName
    test = obj()
TypeError: contour_integral_quad() missing 2 required positional arguments: 'lazy_tensor' and 'rhs'
builder for '/nix/store/fvynsjqnl9x7ak0b6c5g74k3n1c1k78m-python3.9-gpytorch-1.5.0.drv' failed with exit code 1
error: build of '/nix/store/fvynsjqnl9x7ak0b6c5g74k3n1c1k78m-python3.9-gpytorch-1.5.0.drv' failed
```

## Expected Behavior

The test suite to pass.

## System information

**Please complete the following information:**
- gpytorch 1.5.0
- pytorch 1.6.0
- NixOS 20.09.3301.42809feaa9f

## Additional context
n/a

**Comment by gpleiss** [comment]
Apologies for the slow reply. This should be fixed now.
(We had been using `python -m unittest` to run our test suite. `python setup.py test` had not been set up properly until now.)
