### ISSUE TITLE
[Question] Cleanest way to implement a generic distance matrix embedded with the RBF

### ISSUE THREAD

**Issue by vr308** [cornellius-gp/gpytorch#1762]
![Screenshot from 2021-09-20 18-17-49](https://user-images.githubusercontent.com/17442913/134045570-ccf667f1-eaa4-40e4-8bc5-94ddab6a4b05.png)

Want to implement a variation where the $\theta$ matrix is dense. Is the best way to sub-class the RBF kernel and overwrite the forward method? 

The only issue is that it seems like I cant use the helper methods in the [Distance](https://github.com/cornellius-gp/gpytorch/blob/master/gpytorch/kernels/kernel.py#L22) class as I need to insert a dense covariance matrix within the squared distance. 

Any suggestions would be great.

Thanks!

**Comment by andrewgordonwilson** [comment]
One option is to treat it as a simple transformation of your inputs (a special case of deep kernel learning), where x -> Px. Then your covariance matrix for the RBF kernel becomes PP'/theta^2, or more generally PDP' where D is diagonal.

**Comment by vr308** [comment]
Thank you, yes thats certainly one way to parameterise it. 

I am trying to explore learning the positive semi-definite matrix M probabilistically where M = PDP' and even though it seems more sensible to work with this decomposition, for a fully Bayesian approach it seems like it is most natural to think about a prior for psd matrices.

**Comment by wjmaddox** [comment]
This parameterization doesn't preclude a probabilistic treatment, one could think about placing a prior over `M = PDP'` instead? Implementation wise, that kind of prior might be tricky.

**Comment by andrewgordonwilson** [comment]
Yes. If you put a Gaussian prior over P, it will induce a Wishart prior over M=PP', which is the canonical prior over positive definite matrices (assuming M is full rank). If you are working with more than about ten input dimensions, I would recommend low rank PP' plus diagonal.

**Comment by vr308** [comment]
great, thanks @andrewgordonwilson @wjmaddox  so the degree of freedom parameter (k) comes from the column dimensionality of the P matrix (Dxk) where if the data is (NxD) and one "chooses"  k < D and proceeds as in DKL where the inputs are projected x -> Px in the forward pass we are implicitly working with a dense M. And as for the diagonal matrix which learns the typical axis aligned lengthscales one can place an independent prior over those? 

I am starting to see how I can avoid coding up a mahalanobis distance RBF kernel which is a huge relief. :)

**Comment by jacobrgardner** [comment]
Yeah, maybe we should update the fully bayesian example notebook to include a prior over a derived function of a parameter to make this clear.

The setting closure should be a function `set_P_and_D(module, M)` that decomposes M and then sets the value of `module.proj_mat` and `module.covar_module.base_kernel.lengthscale`  (technically `raw_lengthscale` but there's a setter) accordingly.

**Comment by vr308** [comment]
I am able to initialise the model now but the sampler is failing with a very cryptic runtime error pasted below: 

Code: 

```python
def compute_PDP(proj_mat: torch.Tensor, ls: torch.Tensor):

    
    return torch.matmul(proj_mat, torch.eye(2)*ls)

def set_proj_and_lengthscale(module, M):
    
    diag, P = torch.linalg.eigh(M)
    module.covar_module.base_kernel.lengthscale = diag
    module.proj_mat = P

    
class ExactGPModel(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood):
        super(ExactGPModel, self).__init__(train_x, train_y, likelihood)
        
        k = 2
        self.mean_module = gpytorch.means.ConstantMean()
        # Optionally specify ard_num_dims in RBFKernel to get non-constant diagonal matrix D.
        self.covar_module = gpytorch.kernels.ScaleKernel(gpytorch.kernels.RBFKernel(ard_num_dims=train_x.size(-1)))
        
        # P matrix
        self.proj_mat = torch.nn.Parameter(torch.randn(train_x.size(-1), k))
        
        
        wishart_scale = torch.eye(train_x.size(-1))*torch.std(train_x, axis=0) # maybe this can be set more intelligently, dot product kernel?
        
        self.diag_mat = torch.eye(2)*model.covar_module.base_kernel.lengthscale
        M = torch.matmul(torch.matmul(self.proj_mat, self.diag_mat), self.proj_mat.T)

        # Register prior directly on PDP'.
        self.register_prior("mahalanobis_covar", 
                            WishartPrior(k, wishart_scale), 
                            lambda module: compute_PDP(module.proj_mat, model.covar_module.base_kernel.lengthscale),
                            lambda module, M: set_proj_and_lengthscale(module, M))
        
    def forward(self, x):
        x = x @ self.proj_mat   # n x d * d x k --> n x k
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)

if __name__ == "__main__":


    jitter = np.eye(625)*1e-6
    X = np.linspace(-10, 10, 25)
    X_grid = np.meshgrid(X, X)
    X = torch.Tensor(np.vstack((X_grid[0].flatten(), X_grid[1].flatten())).T)
    y = (X**3 - X**2 + X)
    
    likelihood = gpytorch.likelihoods.GaussianLikelihood()
    model = ExactGPModel(X, y, likelihood)  
    
    mll = gpytorch.mlls.ExactMarginalLogLikelihood(likelihood, model)
    
    for i in model.named_parameters():
        print(i)
    
    def pyro_model(x, y):
        model.pyro_sample_from_prior()
        output = model(x)
        loss = mll.pyro_factor(output, y)
        return y
    
    nuts_kernel = NUTS(pyro_model, adapt_step_size=True)
    mcmc_run = MCMC(nuts_kernel, num_samples=100, warmup_steps=200, disable_progbar=False)
    mcmc_run.run(X, y) 
```

Error:
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "<ipython-input-559-29facc6022ce>", line 1, in <module>
    mcmc_run.run(X, y)

  File "/home/vr308/anaconda3/lib/python3.8/site-packages/pyro/poutine/messenger.py", line 12, in _context_wrap
    return fn(*args, **kwargs)

  File "/home/vr308/anaconda3/lib/python3.8/site-packages/pyro/infer/mcmc/api.py", line 563, in run
    for x, chain_id in self.sampler.run(*args, **kwargs):

  File "/home/vr308/anaconda3/lib/python3.8/site-packages/pyro/infer/mcmc/api.py", line 223, in run
    for sample in _gen_samples(

  File "/home/vr308/anaconda3/lib/python3.8/site-packages/pyro/infer/mcmc/api.py", line 144, in _gen_samples
    kernel.setup(warmup_steps, *args, **kwargs)

  File "/home/vr308/anaconda3/lib/python3.8/site-packages/pyro/infer/mcmc/hmc.py", line 325, in setup
    self._initialize_model_properties(args, kwargs)

  File "/home/vr308/anaconda3/lib/python3.8/site-packages/pyro/infer/mcmc/hmc.py", line 259, in _initialize_model_properties
    init_params, potential_fn, transforms, trace = initialize_model(

  File "/home/vr308/anaconda3/lib/python3.8/site-packages/pyro/infer/mcmc/util.py", line 427, in initialize_model
    max_plate_nesting = _guess_max_plate_nesting(model, model_args, model_kwargs)

  File "/home/vr308/anaconda3/lib/python3.8/site-packages/pyro/infer/mcmc/util.py", line 251, in _guess_max_plate_nesting
    model_trace = poutine.trace(model).get_trace(*args, **kwargs)

  File "/home/vr308/anaconda3/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py", line 198, in get_trace
    self(*args, **kwargs)

  File "/home/vr308/anaconda3/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py", line 180, in __call__
    raise exc from e

  File "/home/vr308/anaconda3/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py", line 174, in __call__
    ret = self.fn(*args, **kwargs)

  File "<ipython-input-558-ca6588e1fb01>", line 16, in pyro_model
    model.pyro_sample_from_prior()

  File "/home/vr308/anaconda3/lib/python3.8/site-packages/gpytorch/module.py", line 382, in pyro_sample_from_prior
    new_module = self.to_pyro_random_module()

  File "/home/vr308/anaconda3/lib/python3.8/site-packages/gpytorch/module.py", line 362, in to_pyro_random_module
    new_module = copy.deepcopy(self)

  File "/home/vr308/anaconda3/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)

  File "/home/vr308/anaconda3/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)

  File "/home/vr308/anaconda3/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)

  File "/home/vr308/anaconda3/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)

  File "/home/vr308/anaconda3/lib/python3.8/copy.py", line 153, in deepcopy
    y = copier(memo)

  File "/home/vr308/anaconda3/lib/python3.8/site-packages/torch/_tensor.py", line 55, in __deepcopy__
    raise RuntimeError("Only Tensors created explicitly by the user "

RuntimeError: Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol at the moment
Trace Shapes:
 Param Sites:
Sample Sites:
```

**Comment by vr308** [comment]
no pending questions for now - so will close. thanks.
