### ISSUE TITLE
[Bug] model.cpu() does not move the caches, leading to device error

### ISSUE THREAD

**Issue by saitcakmak** [cornellius-gp/gpytorch#1859]
# 🐛 Bug

Calling `model.cpu()` on a `model` that is originally created on the GPU does not move the caches (e.g., `mean_cache`) to the CPU leading to a `RuntimeError` due to tensors being on different devices. 

## To reproduce

** Code snippet to reproduce **
```python
import torch
import gpytorch


class DummyModel(gpytorch.models.ExactGP):
    def __init__(self, tx, ty, likelihood):
        super(DummyModel, self).__init__(tx, ty, likelihood)
        self.mean_module = gpytorch.means.ConstantMean().to(tx)
        self.covar_module = gpytorch.kernels.RBFKernel().to(tx)

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)


device = "cuda"
tx = torch.rand(10, device=device)
ty = torch.randn(10, device=device)

model = DummyModel(
    tx, ty, likelihood=gpytorch.likelihoods.GaussianLikelihood().to(device=device)
).eval()

test_x = torch.rand(5, device=device)
model(test_x)

cpu_model = model.cpu()
cpu_x = test_x.cpu()
cpu_model(cpu_x)

```

** Stack trace/error message **
```
Traceback (most recent call last):
  File "/home/saitcakmak/PycharmProjects/robust_mobo/test/model_to_test.py", line 31, in <module>
    cpu_model(cpu_x)
  File "/home/saitcakmak/anaconda3/envs/robust_mobo/lib/python3.9/site-packages/gpytorch/models/exact_gp.py", line 319, in __call__
    predictive_mean, predictive_covar = self.prediction_strategy.exact_prediction(full_mean, full_covar)
  File "/home/saitcakmak/anaconda3/envs/robust_mobo/lib/python3.9/site-packages/gpytorch/models/exact_prediction_strategies.py", line 262, in exact_prediction
    self.exact_predictive_mean(test_mean, test_train_covar),
  File "/home/saitcakmak/anaconda3/envs/robust_mobo/lib/python3.9/site-packages/gpytorch/models/exact_prediction_strategies.py", line 280, in exact_predictive_mean
    res = (test_train_covar @ self.mean_cache.unsqueeze(-1)).squeeze(-1)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking arugment for argument mat2 in method wrapper_mm)
```

## Expected Behavior

The `self.mean_cache` should also be on the CPU and the code should run without errors.

## System information

**Please complete the following information:**
GPyTorch: 1.6.0
Torch: 1.9.0
OS: Ubuntu 20.04

## Additional context

Originally ran into this issue using BoTorch models, where I was trying to fall back on CPU to get around some OOM errors.

**Comment by Balandat** [comment]
Hmm I think we can probably inject some logic into the caching code that would check the object for which device/dtype it's on and then if needed move the caches over to the right device / cast to the right dtype. The only thing is that currently I don't think all objects (in particular the `PredictionStrategy` objects) have a consistent API for returning this (`LazyTensor` does). So one thought would be to just add that `device` and `dtype` property to the prediction strategies and then do the conversion of the caches if needed.

@jacobrgardner, @gpleiss  any thoughts on this approach?

**Comment by gpleiss** [comment]
This sounds like a good idea. I can take a stab at this after the holidays.

**Comment by saitcakmak** [comment]
I am running into this issue again. I tried using `model._clear_cache()` to get around it but that only deletes `prediction_strategy` and the `mean_cache` remains the same. I am working with a model that deletes its submodules on `train` call (`SaasFullyBayesianSingleTaskGP`), so doing `model.train().eval()` is not really an option. I am sure I can hack my way around it but it would be good to fix this for good.

**Comment by Turakar** [comment]
Also, leaving the caches on the GPU leads to unnecessary memory usage if you use multiple models.
