### ISSUE TITLE
Question: GridInterpolationVariationalStrategy input for SVDKL

### ISSUE THREAD

**Issue by SimonKitSangChu** [cornellius-gp/gpytorch#1873]
Following the tutorial on [SVDKL on CIFA10/100](https://docs.gpytorch.ai/en/stable/examples/06_PyTorch_NN_Integration_DKL/Deep_Kernel_Learning_DenseNet_CIFAR_Tutorial.html), I am still not sure how to implement SVDKL on a simple MLP feature extractor with `GridInterpolationVariationalStrategy`. In particular, what input does `GridInterpolationVariationalStrategy` take? I.e. `x.shape` =  (n_features, n_samples)?

I assume `GridInterpolationVariationalStrategy` and `ApproximateGP` would help reduce memory usage significantly. ExactGP without SV seems to be less scalable for the dataset of ~20000 samples.

Thanks in advance.
```
class MLP(torch.nn.Sequential):
    def __init__(self, n_dims, n_layers: int = 3, out_dims: Optional[int] = None):
        super().__init__()
        if n_layers:
            for i in range(n_layers-1):
                self.add_module(f'linear_{i}', torch.nn.LazyLinear(n_dims))
                self.add_module(f'relu_{i}', torch.nn.ReLU())

        if out_dims:
            self.add_module('output_layer', torch.nn.LazyLinear(out_dims))
        else:
            self.add_module('output_layer', torch.nn.LazyLinear(n_dims))


class GaussianProcessLayer(gpytorch.models.ApproximateGP):
    def __init__(self, grid_size=64, grid_bounds=(-10, 10)):
        variational_distribution = gpytorch.variational.CholeskyVariationalDistribution(
            num_inducing_points=grid_size
        )
        variational_strategy = gpytorch.variational.GridInterpolationVariationalStrategy(
            self, grid_size=grid_size, grid_bounds=[grid_bounds],
            variational_distribution=variational_distribution,
        )
        super().__init__(variational_strategy)

        self.covar_module = gpytorch.kernels.ScaleKernel(
            gpytorch.kernels.RBFKernel(
                lengthscale_prior=gpytorch.priors.SmoothedBoxPrior(
                    math.exp(-1), math.exp(1), sigma=0.1, transform=torch.exp
                )
            )
        )
        self.mean_module = gpytorch.means.ConstantMean()
        self.grid_bounds = grid_bounds

    def forward(self, x):
        mean = self.mean_module(x)
        covar = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean, covar)


class DKLModel(gpytorch.Module):
    def __init__(self, n_dims, scale_bounds=(-1, 1)):
        super(DKLModel, self).__init__()
        self.feature_extractor = MLP(n_dims)
        self.gp_layer = GaussianProcessLayer()
        self.scale_bounds = scale_bounds
        self.n_dims = n_dims
        self.scale_to_bounds = gpytorch.utils.grid.ScaleToBounds(self.scale_bounds[0], self.scale_bounds[1])

    def forward(self, x):
        x = self.feature_extractor(x)
        x = self.scale_to_bounds(x)
        return self.gp_layer(x)  # x.shape = (n_samples, n_features)
```

Minimal reproducible code
```
import gpytorch
from gpytorch.variational import CholeskyVariationalDistribution
from gpytorch.variational import VariationalStrategy
from sklearn.datasets import fetch_california_housing
import torch
from torch.utils.data import TensorDataset, DataLoader
import tqdm

# settings
training_iterations = 100
n_dims = 8
num_likelihood_samples = 128

# build dataset
dataset = sklearn.datasets.fetch_california_housing(data_home='california_housing')
X, y = dataset['data'], dataset['target']
X, y = torch.tensor(X).float(), torch.tensor(y).float()
dataloader = Dataloader(TensorDataset(X, y), batch_size=16, shuffle=False)

# training
likelihood = gpytorch.likelihoods.GaussianLikelihood().train()
model = DKLModel(n_dims=n_dims).train()

optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
mll = gpytorch.mlls.VariationalELBO(likelihood, model.gp_layer, num_data=X.shape[0])

for epoch in range(1, training_iterations+1):
    minibatch_iter = tqdm.tqdm(train_dataloader, desc=f"(Epoch {epoch}) Minibatch")
    with gpytorch.settings.num_likelihood_samples(num_likelihood_samples):
        for data, target in minibatch_iter:
            optimizer.zero_grad()
            output = model(data)
            loss = -mll(output, target)
            loss.backward()
            optimizer.step()
            minibatch_iter.set_postfix(loss=loss.item())
```

This is the error I receive.
```
(Epoch 1) Minibatch:   0%|                                                    | 0/146 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "exact_dkl.py", line 177, in <module>
    loss.backward()
  File "/home/work/anaconda3/envs/dl/lib/python3.7/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/work/anaconda3/envs/dl/lib/python3.7/site-packages/torch/autograd/__init__.py", line 143, in backward
    grad_tensors_ = _make_grads(tensors, grad_tensors_)
  File "/home/work/anaconda3/envs/dl/lib/python3.7/site-packages/torch/autograd/__init__.py", line 50, in _make_grads
    raise RuntimeError("grad can be implicitly created only for scalar outputs")
RuntimeError: grad can be implicitly created only for scalar outputs
```

**Comment by SimonKitSangChu** [comment]
Or, the shorter questions are
- What input shape does `ApproximateGP` take with `GridInterpolationVariationalStrategy`?
- How to build a variational strategy with `k` dimensional input and a single scalar output?
