### ISSUE TITLE
Dirichlet-based GP for large-scale calibrated classification on multiple GPUs [Bug]

### ISSUE THREAD

**Issue by dejanmi** [cornellius-gp/gpytorch#1952]
# 🐛 Bug

Hi GPyTorch community,

I successfully did the [exact GP regression on classification labels ](https://docs.gpytorch.ai/en/stable/examples/01_Exact_GPs/GP_Regression_on_Classification_Labels.html) example and the [exact GP regression with multiple GPUs and kernel partitioning](https://docs.gpytorch.ai/en/stable/examples/02_Scalable_Exact_GPs/Simple_MultiGPU_GP_Regression.html) example. Now, I tried to combine both examples, i.e. training a Dirichlet-based GP for large-scale calibrated classification on multiple GPUs. Before I dive into the problem, is this even possible?

So basically what I did is, I added a ``MultiDeviceKernel`` to the Dirichlet-based GP model and increased the data to 10k and 100k datapoints. Thereby, I realized that the partitioning during training fails.

## To reproduce

** Code snippet to reproduce **
```python
import gc

import numpy as np
import torch
import gpytorch
from gpytorch.models import ExactGP
from gpytorch.likelihoods import DirichletClassificationLikelihood
from gpytorch.means import ConstantMean
from gpytorch.kernels import ScaleKernel, RBFKernel
from models.LBFGS import FullBatchLBFGS

class DirichletGPModelMultipleGPU(ExactGP):
    def __init__(self, train_x, train_y, likelihood, num_classes, n_devices, output_device):
        super(DirichletGPModelMultipleGPU, self).__init__(train_x, train_y, likelihood)
        self.mean_module = ConstantMean(batch_shape=torch.Size((num_classes,)))
        base_covar_module = ScaleKernel(
            RBFKernel(batch_shape=torch.Size((num_classes,))),
            batch_shape=torch.Size((num_classes,)))

        self.covar_module = gpytorch.kernels.MultiDeviceKernel(
            base_covar_module, device_ids=range(n_devices),
            output_device=output_device
        )

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)

def gen_data(num_data, seed = 2019):
    torch.random.manual_seed(seed)

    x = torch.randn(num_data,1)
    y = torch.randn(num_data,1)

    u = torch.rand(1)
    data_fn = lambda x, y: 1 * torch.sin(0.15 * u * 3.1415 * (x + y)) + 1
    latent_fn = data_fn(x, y)
    z = torch.round(latent_fn).long().squeeze()
    return torch.cat((x,y),dim=1), z, data_fn

def find_best_gpu_setting(model, likelihood, train_x,
                          n_devices,
                          preconditioner_size
                          ):
    N = train_x.size(0)

    # Find the optimum partition/checkpoint size by decreasing in powers of 2
    # Start with no partitioning (size = 0)
    checkpoint_size = [0]
    settings = [0] + [int(n) for n in np.ceil(N / 2 ** np.arange(1, np.floor(np.log2(N))))]
    for checkpoint_size in settings:
        print('Number of devices: {} -- Kernel partition size: {}'.format(n_devices, checkpoint_size))
        try:
            # Try a full forward and backward pass with this setting to check memory usage
            _, _ = train_multiple_gpu(model, likelihood, train_x, n_devices=n_devices,
                                      checkpoint_size=checkpoint_size,
                                      preconditioner_size=preconditioner_size, n_training_iter=1)

            # when successful, break out of for-loop and jump to finally block
            break
        except RuntimeError as e:
            print('RuntimeError: {}'.format(e))
        except AttributeError as e:
            print('AttributeError: {}'.format(e))
        finally:
            # handle CUDA OOM error
            gc.collect()
            torch.cuda.empty_cache()
    return checkpoint_size

def train_multiple_gpu(model, likelihood, train_x, n_devices, checkpoint_size,
                       preconditioner_size,
                       n_training_iter):
    model.train()
    likelihood.train()

    optimizer = FullBatchLBFGS(model.parameters(), lr=0.1)
    mll = gpytorch.mlls.ExactMarginalLogLikelihood(likelihood, model)

    with gpytorch.beta_features.checkpoint_kernel(checkpoint_size), \
            gpytorch.settings.max_preconditioner_size(preconditioner_size):

        def closure():
            optimizer.zero_grad()
            output = model(train_x)
            loss = -mll(output, likelihood.transformed_targets).sum()
            return loss

        loss = closure()
        loss.backward()

        for i in range(n_training_iter):
            options = {'closure': closure, 'current_loss': loss, 'max_ls': 10}
            loss, _, _, _, _, _, _, fail = optimizer.step(options)
            print('Iter %d/%d - Loss: %.3f' % (
                i + 1, n_training_iter, loss.item()))

            if fail:
                print('Convergence reached!')
                break

    print(f"Finished training on {train_x.size(0)} data points using {n_devices} GPUs.")

    return model, likelihood

def gp_rbf_model_multiple_gpu():
    output_device = torch.device('cuda:0')
    train_x, train_y, genfn = gen_data(10000)
    train_x, train_y = train_x.contiguous(), train_y.contiguous()
    train_x, train_y = train_x.to(output_device), train_y.to(output_device)
    n_devices = 4
    print('Planning to run on {} GPUs.'.format(n_devices))

    likelihood = DirichletClassificationLikelihood(targets=train_y, learn_additional_noise=True)
    likelihood = likelihood.to(output_device)
    model = DirichletGPModelMultipleGPU(train_x, likelihood.transformed_targets, likelihood,
                             num_classes=likelihood.num_classes,
                             n_devices=n_devices, output_device=output_device)
    model = model.to(output_device)
    preconditioner_size = 100
    checkpoint_size = find_best_gpu_setting(model, likelihood, train_x,
                                            n_devices=n_devices,
                                            preconditioner_size=preconditioner_size)
    model, likelihood = train_multiple_gpu(model, likelihood, train_x, n_devices,
                                           checkpoint_size, preconditioner_size, 20)

if __name__ == '__main__':
    gp_rbf_model_multiple_gpu()

```

** Stack trace/error message **
```
Planning to run on 4 GPUs.
Number of devices: 4 -- Kernel partition size: 0
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:3 and cuda:1! (when checking arugment for argument tensors in method wrapper__cat)
Number of devices: 4 -- Kernel partition size: 5000
RuntimeError: Attempting to tensor index a non-batch matrix's batch dimensions. Got batch index (tensor([[0, 0, 0,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1],
        [2, 2, 2,  ..., 2, 2, 2]], device='cuda:0'),) but my shape was torch.Size([3, 10000, 10000])
Number of devices: 4 -- Kernel partition size: 2500
RuntimeError: Attempting to tensor index a non-batch matrix's batch dimensions. Got batch index (tensor([[0, 0, 0,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1],
        [2, 2, 2,  ..., 2, 2, 2]], device='cuda:0'),) but my shape was torch.Size([3, 10000, 10000])
Number of devices: 4 -- Kernel partition size: 1250
RuntimeError: Attempting to tensor index a non-batch matrix's batch dimensions. Got batch index (tensor([[0, 0, 0,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1],
        [2, 2, 2,  ..., 2, 2, 2]], device='cuda:0'),) but my shape was torch.Size([3, 10000, 10000])
Number of devices: 4 -- Kernel partition size: 625
RuntimeError: Attempting to tensor index a non-batch matrix's batch dimensions. Got batch index (tensor([[0, 0, 0,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1],
        [2, 2, 2,  ..., 2, 2, 2]], device='cuda:0'),) but my shape was torch.Size([3, 10000, 10000])
Number of devices: 4 -- Kernel partition size: 313
RuntimeError: Attempting to tensor index a non-batch matrix's batch dimensions. Got batch index (tensor([[0, 0, 0,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1],
        [2, 2, 2,  ..., 2, 2, 2]], device='cuda:0'),) but my shape was torch.Size([3, 10000, 10000])
Number of devices: 4 -- Kernel partition size: 157
RuntimeError: Attempting to tensor index a non-batch matrix's batch dimensions. Got batch index (tensor([[0, 0, 0,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1],
        [2, 2, 2,  ..., 2, 2, 2]], device='cuda:0'),) but my shape was torch.Size([3, 10000, 10000])
Number of devices: 4 -- Kernel partition size: 79
RuntimeError: Attempting to tensor index a non-batch matrix's batch dimensions. Got batch index (tensor([[0, 0, 0,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1],
        [2, 2, 2,  ..., 2, 2, 2]], device='cuda:0'),) but my shape was torch.Size([3, 10000, 10000])
Number of devices: 4 -- Kernel partition size: 40
RuntimeError: Attempting to tensor index a non-batch matrix's batch dimensions. Got batch index (tensor([[0, 0, 0,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1],
        [2, 2, 2,  ..., 2, 2, 2]], device='cuda:0'),) but my shape was torch.Size([3, 10000, 10000])
Number of devices: 4 -- Kernel partition size: 20
RuntimeError: Attempting to tensor index a non-batch matrix's batch dimensions. Got batch index (tensor([[0, 0, 0,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1],
        [2, 2, 2,  ..., 2, 2, 2]], device='cuda:0'),) but my shape was torch.Size([3, 10000, 10000])
Number of devices: 4 -- Kernel partition size: 10
RuntimeError: Attempting to tensor index a non-batch matrix's batch dimensions. Got batch index (tensor([[0, 0, 0,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1],
        [2, 2, 2,  ..., 2, 2, 2]], device='cuda:0'),) but my shape was torch.Size([3, 10000, 10000])
Number of devices: 4 -- Kernel partition size: 5
RuntimeError: Attempting to tensor index a non-batch matrix's batch dimensions. Got batch index (tensor([[0, 0, 0,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1],
        [2, 2, 2,  ..., 2, 2, 2]], device='cuda:0'),) but my shape was torch.Size([3, 10000, 10000])
Number of devices: 4 -- Kernel partition size: 3
RuntimeError: Attempting to tensor index a non-batch matrix's batch dimensions. Got batch index (tensor([[0, 0, 0,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1],
        [2, 2, 2,  ..., 2, 2, 2]], device='cuda:0'),) but my shape was torch.Size([3, 10000, 10000])
Traceback (most recent call last):
  File "/home/dejanmi/virtualenv_remote_sm/lib/python3.7/site-packages/gpytorch/lazy/lazy_evaluated_kernel_tensor.py", line 111, in _getitem
    x1 = x1[(*batch_indices, row_index, dim_index)]
IndexError: too many indices for tensor of dimension 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dejanmi/remote_sm/src/models/test_classification.py", line 129, in <module>
    gp_rbf_model_multiple_gpu()
  File "/home/dejanmi/remote_sm/src/models/test_classification.py", line 126, in gp_rbf_model_multiple_gpu
    checkpoint_size, preconditioner_size, 20)
  File "/home/dejanmi/remote_sm/src/models/test_classification.py", line 90, in train_multiple_gpu
    loss = closure()
  File "/home/dejanmi/remote_sm/src/models/test_classification.py", line 87, in closure
    loss = -mll(output, likelihood.transformed_targets).sum()
  File "/home/dejanmi/virtualenv_remote_sm/lib/python3.7/site-packages/gpytorch/module.py", line 30, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/dejanmi/virtualenv_remote_sm/lib/python3.7/site-packages/gpytorch/mlls/exact_marginal_log_likelihood.py", line 62, in forward
    res = output.log_prob(target)
  File "/home/dejanmi/virtualenv_remote_sm/lib/python3.7/site-packages/gpytorch/distributions/multivariate_normal.py", line 169, in log_prob
    inv_quad, logdet = covar.inv_quad_logdet(inv_quad_rhs=diff.unsqueeze(-1), logdet=True)
  File "/home/dejanmi/virtualenv_remote_sm/lib/python3.7/site-packages/gpytorch/lazy/lazy_tensor.py", line 1344, in inv_quad_logdet
    *args,
  File "/home/dejanmi/virtualenv_remote_sm/lib/python3.7/site-packages/gpytorch/functions/_inv_quad_log_det.py", line 67, in forward
    preconditioner, precond_lt, logdet_correction = lazy_tsr._preconditioner()
  File "/home/dejanmi/virtualenv_remote_sm/lib/python3.7/site-packages/gpytorch/lazy/added_diag_lazy_tensor.py", line 100, in _preconditioner
    self._piv_chol_self = pivoted_cholesky.pivoted_cholesky(self._lazy_tensor, max_iter)
  File "/home/dejanmi/virtualenv_remote_sm/lib/python3.7/site-packages/gpytorch/utils/pivoted_cholesky.py", line 66, in pivoted_cholesky
    row = matrix[(*batch_iters, pi_m.view(-1), slice(None, None, None))]
  File "/home/dejanmi/virtualenv_remote_sm/lib/python3.7/site-packages/gpytorch/lazy/lazy_evaluated_kernel_tensor.py", line 401, in __getitem__
    return super().__getitem__(index)
  File "/home/dejanmi/virtualenv_remote_sm/lib/python3.7/site-packages/gpytorch/lazy/lazy_tensor.py", line 2199, in __getitem__
    res = self._get_indices(row_index, col_index, *batch_indices)
  File "/home/dejanmi/virtualenv_remote_sm/lib/python3.7/site-packages/gpytorch/lazy/lazy_tensor.py", line 311, in _get_indices
    base_lazy_tensor = self._getitem(_noop_index, _noop_index, *batch_indices)._expand_batch(final_shape)
  File "/home/dejanmi/virtualenv_remote_sm/lib/python3.7/site-packages/gpytorch/lazy/lazy_evaluated_kernel_tensor.py", line 117, in _getitem
    "Attempting to tensor index a non-batch matrix's batch dimensions. "
RuntimeError: Attempting to tensor index a non-batch matrix's batch dimensions. Got batch index (tensor([[0, 0, 0,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1],
        [2, 2, 2,  ..., 2, 2, 2]], device='cuda:0'),) but my shape was torch.Size([3, 10000, 10000])

Process finished with exit code 1

```

## Expected Behavior

I expected to run the Dirichlet-based GP model on multiple GPUs, but the partitioning failed.

## System information

**Please complete the following information:**
- GPyTorch Version: 1.6.0
- PyTorch Version: 1.9.0+cu102
- Python Version: 3.7.8
- Computer OS: Ubuntu 16.04.6 LTS (Xenial Xerus)

**Comment by gpleiss** [comment]
Closing because checkpointing is now deprecated (as of v1.11)
