### ISSUE TITLE
[Bug] Multi-Class Classification

### ISSUE THREAD

**Issue by borishamlin** [cornellius-gp/gpytorch#1956]
# 🐛 Error when performing simple multi-class classification

First-timer here--- apologies if my report is not standard format!

I am simply trying to do a vanilla multi-class classification, and from #1423 the advice is simply to follow [this tutorial](https://docs.gpytorch.ai/en/stable/examples/04_Variational_and_Approximate_GPs/SVGP_Multitask_GP_Regression.html), but replace `gpytorch.likelihoods.MultitaskGaussianLikelihood` with `gpytorch.likelihoods.SoftmaxLikelihood`.

As a first attempt, I am simply using **two classes** for the label space. I understand that there is technically no need to use softmax in this scenario, but I wanted to make this work for two classes before I increase to three or more. Hence, I have first produced a working example for **not** using softmax:

## Not Using Softmax

The following works fine:

```python
import math
import torch
import random
import numpy as np
import gpytorch as gp

from matplotlib import pyplot as plt

random.seed(0)
np.random.seed(0)
torch.manual_seed(0)

from sklearn.datasets import make_moons

X, y = make_moons(noise = 0.3)
X_train = torch.from_numpy(X).float()
y_train = torch.from_numpy(y).float()

class GPClassificationModel(gp.models.ApproximateGP):
    def __init__(self, X_train):
        variational_distribution = gp.variational.CholeskyVariationalDistribution(
            X_train.size(0)
        )
        variational_strategy = gp.variational.VariationalStrategy(
            self, X_train, variational_distribution, learn_inducing_locations = True
        )

        super(GPClassificationModel, self).__init__(variational_strategy)

        self.mean_module = gp.means.ConstantMean()
        self.covar_module = gp.kernels.ScaleKernel(gp.kernels.RBFKernel())

    def forward(self, X):
        mean_X = self.mean_module(X)
        covar_X = self.covar_module(X)

        return gp.distributions.MultivariateNormal(mean_X, covar_X)

likelihood = gp.likelihoods.BernoulliLikelihood()
model = GPClassificationModel(X_train)

likelihood.train()
model.train()

train_iter = 50

optimizer = torch.optim.Adam(model.parameters(), lr = 0.1)

marginal_log_likelihood = gp.mlls.VariationalELBO(likelihood, model, y_train.numel())

for i in range(train_iter):
    optimizer.zero_grad()

    f_post = model(X_train)
    loss = - marginal_log_likelihood(f_post, y_train)
    loss.backward()

    print('Iter %d/%d - Loss: %.3f' % (i + 1, train_iter, loss.item()))
    optimizer.step()
```

Then I can plot the result:

```python
likelihood.eval()
model.eval()

h = 0.05
x1_min, x1_max = X[:, 0].min() - 0.5, X[:, 0].max() + 0.5
x2_min, x2_max = X[:, 1].min() - 0.5, X[:, 1].max() + 0.5
xx1, xx2 = np.meshgrid(np.arange(x1_min, x1_max, h), np.arange(x2_min, x2_max, h))

with torch.no_grad():
    X_test = torch.from_numpy(np.vstack((xx1.reshape(-1), xx2.reshape(-1))).T).float()
    f_pred = model(X_test)
    y_pred = likelihood(f_pred)

with torch.no_grad():
    fg, ax = plt.subplots(1, 1, figsize = (4, 3))

    ax.contourf(xx1, xx2, y_pred.mean.numpy().reshape(xx1.shape), levels = 16)
    ax.scatter(X_train[y_train == 0, 0], X_train[y_train == 0, 1])
    ax.scatter(X_train[y_train == 1, 0], X_train[y_train == 1, 1])

    plt.show()
```

![Figure_1](https://user-images.githubusercontent.com/94037340/159929778-d579b4d1-2e72-4017-8cef-283907ed4074.png)

## Using Softmax

Next, now I want to use softmax, but basically obtain the same result. (If this works, then I can easily generalize to three or more classes). However, the following does not work, even though I follow exactly the instructions given in #1423:

```python
import math
import torch
import random
import numpy as np
import gpytorch as gp

from matplotlib import pyplot as plt

random.seed(0)
np.random.seed(0)
torch.manual_seed(0)

from sklearn.datasets import make_moons

X, y = make_moons(noise = 0.3)
X_train = torch.from_numpy(X).float()
one_hot = np.zeros((len(y), y.max() + 1))
one_hot[np.arange(len(y)), y] = 1
y_train = torch.from_numpy(one_hot).float()

num_classes = 2
num_latents = 3

class GPClassificationModel(gp.models.ApproximateGP):
    def __init__(self):
        inducing_points = torch.rand(num_latents, 16, 2)

        variational_distribution = gp.variational.CholeskyVariationalDistribution(
            inducing_points.size(-2), batch_shape = torch.Size([num_latents])
        )
        variational_strategy = gp.variational.LMCVariationalStrategy(
            gp.variational.VariationalStrategy(
                self, inducing_points, variational_distribution, learn_inducing_locations = True
            ),
            num_tasks = num_classes,
            num_latents = num_latents,
            latent_dim = -1
        )

        super(GPClassificationModel, self).__init__(variational_strategy)

        self.mean_module = gp.means.ConstantMean(
            batch_shape = torch.Size([num_latents])
        )
        self.covar_module = gp.kernels.ScaleKernel(
            gp.kernels.RBFKernel(batch_shape = torch.Size([num_latents])),
            batch_shape = torch.Size([num_latents])
        )

    def forward(self, X):
        mean_X = self.mean_module(X)
        covar_X = self.covar_module(X)

        return gp.distributions.MultivariateNormal(mean_X, covar_X)

likelihood = gp.likelihoods.SoftmaxLikelihood(num_classes = num_classes, mixing_weights = False)
model = GPClassificationModel()

likelihood.train()
model.train()

train_iter = 50

optimizer = torch.optim.Adam([
    {'params': model.parameters()},
    {'params': likelihood.parameters()},
], lr = 0.1)

marginal_log_likelihood = gp.mlls.VariationalELBO(likelihood, model, y_train.size(0))

for i in range(train_iter):
    optimizer.zero_grad()

    f_post = model(X_train)
    loss = - marginal_log_likelihood(f_post, y_train)
    loss.backward()

    print('Iter %d/%d - Loss: %.3f' % (i + 1, train_iter, loss.item()))
    optimizer.step()
```

This gives the following stack trace/error message:

```
Traceback (most recent call last):
  File "gps.py", line 75, in <module>
    loss = - marginal_log_likelihood(f_post, y_train)
  File "~/miniconda/envs/supp/lib/python3.8/site-packages/gpytorch/module.py", line 30, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "~/miniconda/envs/supp/lib/python3.8/site-packages/gpytorch/mlls/variational_elbo.py", line 77, in forward
    return super().forward(variational_dist_f, target, **kwargs)
  File "~/miniconda/envs/supp/lib/python3.8/site-packages/gpytorch/mlls/_approximate_mll.py", line 57, in forward
    log_likelihood = self._log_likelihood_term(approximate_dist_f, target, **kwargs).div(num_batch)
  File "~/miniconda/envs/supp/lib/python3.8/site-packages/gpytorch/mlls/variational_elbo.py", line 61, in _log_likelihood_term
    return self.likelihood.expected_log_prob(target, variational_dist_f, **kwargs).sum(-1)
  File "~/miniconda/envs/supp/lib/python3.8/site-packages/gpytorch/likelihoods/likelihood.py", line 39, in expected_log_prob
    res = likelihood_samples.log_prob(observations).mean(dim=0)
  File "~/miniconda/envs/supp/lib/python3.8/site-packages/torch/distributions/categorical.py", line 117, in log_prob
    self._validate_sample(value)
  File "~/miniconda/envs/supp/lib/python3.8/site-packages/torch/distributions/distribution.py", line 274, in _validate_sample
    raise ValueError('Value is not broadcastable with batch_shape+event_shape: {} vs {}.'.
ValueError: Value is not broadcastable with batch_shape+event_shape: torch.Size([100, 2]) vs torch.Size([10, 100]).
```

## System Information

```
blas                      1.0                         mkl
brotli                    1.0.9                h0d85af4_6    conda-forge
brotli-bin                1.0.9                h0d85af4_6    conda-forge
brotlipy                  0.7.0           py38h9ed2024_1003
bzip2                     1.0.8                h1de35cc_0
ca-certificates           2021.10.8            h033912b_0    conda-forge
certifi                   2021.10.8        py38h50d1736_1    conda-forge
cffi                      1.15.0           py38hc55c11b_1
charset-normalizer        2.0.4              pyhd3eb1b0_0
cryptography              36.0.0           py38hf6deb26_0
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
ffmpeg                    4.3                  h0a44026_0    pytorch
fonttools                 4.31.2           py38hed1de0f_0    conda-forge
freetype                  2.11.0               hd8bbffd_0
gettext                   0.21.0               h7535e17_0
giflib                    5.2.1                haf1e3a3_0
gmp                       6.2.1                h23ab428_2
gnutls                    3.6.15               hed9c0bf_0
gpytorch                  1.6.0                         0    gpytorch
icu                       58.2                 h0a44026_3
idna                      3.3                pyhd3eb1b0_0
intel-openmp              2021.4.0          hecd8cb5_3538
joblib                    1.1.0              pyhd3eb1b0_0
jpeg                      9d                   h9ed2024_0
kiwisolver                1.3.2            py38he9d5cce_0
lame                      3.100                h1de35cc_0
lcms2                     2.12                 hf1fd2bf_0
libbrotlicommon           1.0.9                h0d85af4_6    conda-forge
libbrotlidec              1.0.9                h0d85af4_6    conda-forge
libbrotlienc              1.0.9                h0d85af4_6    conda-forge
libcxx                    12.0.0               h2f01273_0
libffi                    3.3                  hb1e8313_2
libgfortran               3.0.1                h93005f0_2
libiconv                  1.16                 h1de35cc_0
libidn2                   2.3.2                h9ed2024_0
libpng                    1.6.37               ha441bb4_0
libtasn1                  4.16.0               h9ed2024_0
libtiff                   4.2.0                h87d7836_0
libunistring              0.9.10               h9ed2024_0
libuv                     1.40.0               haf1e3a3_0
libwebp                   1.2.2                h56c3ce4_0
libwebp-base              1.2.2                hca72f7f_0
libxml2                   2.9.12               hcdb78fc_0
llvm-openmp               12.0.0               h0dcd299_1
lz4-c                     1.9.3                h23ab428_1
matplotlib                3.5.1            py38h50d1736_0    conda-forge
matplotlib-base           3.5.1            py38hc7d2367_0    conda-forge
mkl                       2021.4.0           hecd8cb5_637
mkl-service               2.4.0            py38h9ed2024_0
mkl_fft                   1.3.1            py38h4ab4a9b_0
mkl_random                1.2.2            py38hb2f4e1b_0
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncurses                   6.3                  hca72f7f_2
nettle                    3.7.3                h230ac6f_1
numpy                     1.21.2           py38h4b4dc7a_0
numpy-base                1.21.2           py38he0bd621_0
openh264                  2.1.1                h8346a28_0
openssl                   1.1.1l               h0d85af4_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pillow                    9.0.1            py38hde71d04_0
pip                       21.2.4           py38hecd8cb5_0
pycparser                 2.21               pyhd3eb1b0_0
pyopenssl                 22.0.0             pyhd3eb1b0_0
pyparsing                 3.0.7              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1                    py38_1
python                    3.8.12               h88f2d9e_0
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytorch                   1.11.0                  py3.8_0    pytorch
readline                  8.1.2                hca72f7f_1
requests                  2.27.1             pyhd3eb1b0_0
scikit-learn              1.0.2            py38hae1ba45_1
scipy                     1.7.3            py38h8c7af03_0
setuptools                58.0.4           py38hecd8cb5_0
six                       1.16.0             pyhd3eb1b0_1
sqlite                    3.37.2               h707629a_0
threadpoolctl             2.2.0              pyh0d69192_0
tk                        8.6.11               h7bc2e8c_0
torchaudio                0.11.0                 py38_cpu    pytorch
torchvision               0.12.0                 py38_cpu    pytorch
tornado                   6.1              py38h96a0964_2    conda-forge
typing_extensions         4.1.1              pyh06a4308_0
unicodedata2              14.0.0           py38h96a0964_0    conda-forge
urllib3                   1.26.8             pyhd3eb1b0_0
wheel                     0.37.1             pyhd3eb1b0_0
xz                        5.2.5                h1de35cc_0
zlib                      1.2.11               h4dc903c_4
zstd                      1.4.9                h322a384_0
```

## Context

I am simply trying to do the most basic task: Classification with GPs. Sorry if my question is silly, but I have tried to investigate myself for a while, and cannot figure out what is the issue!

Thank you so much!!!

**Comment by wjmaddox** [comment]
This is because `SoftmaxLikelihood` actually doesn't expect one-hot encodings but rather class numbers. 

Changing the targets to `y_train = torch.where(y_train)[1]` resolves the error.

**Comment by crasanders** [comment]
I'm also trying to do multiclass classification, and I stumbled upon this example. I was able to train the second model using `SoftmaxLikelihood` by making the suggested change to targets, but I can't figure out how to plot the predictions. `y_pred.mean` returns a bunch of nans, which I guess makes sense because the mean of a categorical distribution doesn't make sense, but I can't figure out the correct way to get the class probabilities.

**Comment by gpleiss** [comment]
> I can't figure out how to plot the predictions

What in particular do you want to plot? The max class probability?

In any case, since this is not an issue or a feature request, please open up a [discussion](https://github.com/cornellius-gp/gpytorch/discussions) if you wish to discuss this further.
