### ISSUE TITLE
test_spectral_mixture_gp_mean_abs_error numerically sensitive

### ISSUE THREAD

**Issue by colesbury** [cornellius-gp/gpytorch#200]
Should TestSpectralMixtureGPRegression.test_spectral_mixture_gp_mean_abs_error use double-precision tensors?

I'm seeing failures in `TestSpectralMixtureGPRegression.test_spectral_mixture_gp_mean_abs_error` on machines that don't have the FMA3 instruction set. If you're using MKL, you can reproduce this by setting the environment variable `MKL_ENABLE_INSTRUCTIONS=AVX` to disable AVX2 and FMA3 instructions in MKL.

The difference is how this line is computed in `adam.py`, specifically the `add_` call:

`exp_avg.mul_(beta1).add_(1 - beta1, grad)`
https://github.com/pytorch/pytorch/blob/4b0098f3ae1a445760f1bf743e1accbf7ae70b56/torch/optim/adam.py#L92

In this case we have `beta1 = 0.9` and effectively compute:

```
exp_avg = exp_avg + 0.1 * grad
```

With FMA3 the multiply and add are computed with full precision and then rounded. Without the FMA3 instructions, the intermediate multiplication is rounded.

I'm also seeing failures with other seeds even with FMA3. For example, if you replace `4` with `7846462` in `TestSpectralMixtureGPRegression.setUp`.

```
ERROR: test_spectral_mixture_gp_mean_abs_error (__main__.TestSpectralMixtureGPRegression)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/examples/test_spectral_mixture_gp_regression.py", line 93, in test_spectral_mixture_gp_mean_abs_error
    loss = -mll(output, train_y)
  File "/data/users/sgross/gpytorch/gpytorch/module.py", line 192, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/data/users/sgross/gpytorch/gpytorch/mlls/exact_marginal_log_likelihood.py", line 35, in forward
    inv_quad, log_det = covar.inv_quad_log_det(inv_quad_rhs=(target - mean).unsqueeze(-1), log_det=True)
  File "/data/users/sgross/gpytorch/gpytorch/lazy/lazy_variable.py", line 583, in inv_quad_log_det
    )(*args)
  File "/data/users/sgross/gpytorch/gpytorch/functions/_inv_quad_log_det.py", line 129, in forward
    eigenvalues, eigenvectors = lanczos_tridiag_to_diag(t_mat)
  File "/data/users/sgross/gpytorch/gpytorch/utils/lanczos.py", line 170, in lanczos_tridiag_to_diag
    return batch_symeig(t_mat)
  File "/data/users/sgross/gpytorch/gpytorch/utils/eig.py", line 23, in batch_symeig
    evals, evecs = mat[i, j].symeig(eigenvectors=True)
RuntimeError: Lapack Error syev : 14 off-diagonal elements didn't converge to zero at /home/sgross/local/pytorch/aten/src/TH/generic/THTensorLapack.cpp:395
```

**Comment by jacobrgardner** [comment]
I think this is solved for the moment by #201
