### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by valentinecesbio** [cornellius-gp/gpytorch#2048]
# 🐛 Bug

I am using a multi-class GP model to perform classification (`gpytorch.models.ApproximateGP`) with the variational strategy `gpytorch.variational.LMCVariationalStrategy` and the variational distribution `gpytorch.variational.CholeskyVariationalDistribution`.

I am using GPU resources for training and prediction. 

When I am using the node A (see below for description), my model is trained correctly without any warning or error.

When I am using the node B (see below for description), my model can't be trained, I got the following error:

```
/work/scratch/belletv/condaEnvs/iota2_otb8/lib/python3.9/site-packages/gpytorch/distributions/multivariate_normal.py:259: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/work/scratch/belletv/condaEnvs/iota2_otb8/lib/python3.9/site-packages/gpytorch/distributions/multivariate_normal.py:259: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/work/scratch/belletv/condaEnvs/iota2_otb8/lib/python3.9/site-packages/gpytorch/distributions/multivariate_normal.py:259: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/work/scratch/belletv/condaEnvs/iota2_otb8/lib/python3.9/site-packages/gpytorch/distributions/multivariate_normal.py:259: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/work/scratch/belletv/condaEnvs/iota2_otb8/lib/python3.9/site-packages/gpytorch/distributions/multivariate_normal.py:259: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/work/scratch/belletv/condaEnvs/iota2_otb8/lib/python3.9/site-packages/gpytorch/distributions/multivariate_normal.py:259: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
/work/scratch/belletv/condaEnvs/iota2_otb8/lib/python3.9/site-packages/gpytorch/distributions/multivariate_normal.py:259: NumericalWarning: Negative variance values detected. This is likely due to numerical instabilities. Rounding negative variances up to 1e-06.
  warnings.warn(
Traceback (most recent call last):
  File "/work/OT/theia/oso/belletv/southfrance_gpytorch/source/classification_southfrance_GP.py", line 430, in <module>
    main()
  File "/work/OT/theia/oso/belletv/southfrance_gpytorch/source/classification_southfrance_GP.py", line 333, in main
    training_GP(model_GP, likelihoodSoftmax,
  File "/work/OT/theia/oso/belletv/southfrance_gpytorch/source/classification_utils.py", line 679, in training_GP
    loss = -mll(output, y_batch)
  File "/work/scratch/belletv/condaEnvs/iota2_otb8/lib/python3.9/site-packages/gpytorch/module.py", line 30, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/work/scratch/belletv/condaEnvs/iota2_otb8/lib/python3.9/site-packages/gpytorch/mlls/variational_elbo.py", line 77, in forward
    return super().forward(variational_dist_f, target, **kwargs)
  File "/work/scratch/belletv/condaEnvs/iota2_otb8/lib/python3.9/site-packages/gpytorch/mlls/_approximate_mll.py", line 57, in forward
    log_likelihood = self._log_likelihood_term(approximate_dist_f, target, **kwargs).div(num_batch)
  File "/work/scratch/belletv/condaEnvs/iota2_otb8/lib/python3.9/site-packages/gpytorch/mlls/variational_elbo.py", line 61, in _log_likelihood_term
    return self.likelihood.expected_log_prob(target, variational_dist_f, **kwargs).sum(-1)
  File "/work/scratch/belletv/condaEnvs/iota2_otb8/lib/python3.9/site-packages/gpytorch/likelihoods/likelihood.py", line 38, in expected_log_prob
    likelihood_samples = self._draw_likelihood_samples(function_dist, *args, **kwargs)
  File "/work/scratch/belletv/condaEnvs/iota2_otb8/lib/python3.9/site-packages/gpytorch/likelihoods/likelihood.py", line 35, in _draw_likelihood_samples
    return self.forward(function_samples, *args, **kwargs)
  File "/work/scratch/belletv/condaEnvs/iota2_otb8/lib/python3.9/site-packages/gpytorch/likelihoods/softmax_likelihood.py", line 67, in forward
    res = base_distributions.Categorical(logits=mixed_fs)
  File "/work/scratch/belletv/condaEnvs/iota2_otb8/lib/python3.9/site-packages/torch/distributions/categorical.py", line 64, in __init__
    super(Categorical, self).__init__(batch_shape, validate_args=validate_args)
  File "/work/scratch/belletv/condaEnvs/iota2_otb8/lib/python3.9/site-packages/torch/distributions/distribution.py", line 55, in __init__
    raise ValueError(
ValueError: Expected parameter logits (Tensor of shape (10, 10, 21)) of distribution Categorical(logits: torch.Size([10, 10, 21])) to satisfy the constraint IndependentConstraint(Real(), 1), but found invalid values:
tensor([[[-2.1255e+01, -2.6087e+01, -8.0084e+00,  ..., -4.7995e-02,
          -7.8764e+00, -1.4917e+01],
         [-1.8171e+01, -1.0026e+01, -1.1238e+01,  ..., -2.3379e+01,
          -1.4504e+01, -1.0412e+01],
         [-6.5785e+00, -3.2766e+00, -3.0235e+00,  ..., -9.7760e+00,
          -9.5838e-01, -7.8572e+00],
         ...,
         [        nan,         nan,         nan,  ...,         nan,
                  nan,         nan],
         [        nan,         nan,         nan,  ...,         nan,
                  nan,         nan],
         [        nan,         nan,         nan,  ...,         nan,
                  nan,         nan]],

        [[-2.3413e+01, -3.1136e+01, -8.5123e+00,  ..., -4.9734e-03,
          -7.1708e+00, -1.2906e+01],
         [-1.7412e+01, -1.0609e+01, -9.9066e+00,  ..., -2.2278e+01,
          -1.5981e+01, -1.0451e+01],
         [-8.0592e+00, -4.1554e+00, -4.2318e+00,  ..., -9.6920e+00,
          -1.1580e-01, -9.9983e+00],
         ...,
         [        nan,         nan,         nan,  ...,         nan,
                  nan,         nan],
         [        nan,         nan,         nan,  ...,         nan,
                  nan,         nan],
         [        nan,         nan,         nan,  ...,         nan,
                  nan,         nan]],

        [[-1.9374e+01, -2.6196e+01, -8.1930e+00,  ..., -4.5800e-01,
          -1.5080e+01, -1.0985e+01],
         [-1.8255e+01, -9.3844e+00, -1.0342e+01,  ..., -2.0605e+01,
          -1.3893e+01, -9.4406e+00],
         [-8.6352e+00, -5.0836e+00, -4.5337e+00,  ..., -1.0992e+01,
          -1.6408e-01, -8.9000e+00],
         ...,
         [        nan,         nan,         nan,  ...,         nan,
                  nan,         nan],
         [        nan,         nan,         nan,  ...,         nan,
                  nan,         nan],
         [        nan,         nan,         nan,  ...,         nan,
                  nan,         nan]],

        ...,

        [[-2.2092e+01, -3.0200e+01, -1.1833e+01,  ..., -8.8911e-03,
          -1.7896e+01, -1.4908e+01],
         [-2.0035e+01, -1.0358e+01, -1.1417e+01,  ..., -2.1812e+01,
          -1.2897e+01, -8.9612e+00],
         [-7.5084e+00, -4.0953e+00, -4.1308e+00,  ..., -9.2520e+00,
          -3.6900e-01, -8.7746e+00],
         ...,
         [        nan,         nan,         nan,  ...,         nan,
                  nan,         nan],
         [        nan,         nan,         nan,  ...,         nan,
                  nan,         nan],
         [        nan,         nan,         nan,  ...,         nan,
                  nan,         nan]],

        [[-2.2527e+01, -2.9638e+01, -7.8131e+00,  ..., -1.6649e-01,
          -1.2978e+01, -1.2057e+01],
         [-1.4053e+01, -8.0834e+00, -7.4548e+00,  ..., -2.0880e+01,
          -1.4399e+01, -9.8272e+00],
         [-7.1327e+00, -2.7557e+00, -3.3486e+00,  ..., -9.3051e+00,
          -5.9334e-01, -8.3687e+00],
         ...,
         [        nan,         nan,         nan,  ...,         nan,
                  nan,         nan],
         [        nan,         nan,         nan,  ...,         nan,
                  nan,         nan],
         [        nan,         nan,         nan,  ...,         nan,
                  nan,         nan]],

        [[-2.6591e+01, -3.5803e+01, -1.3918e+01,  ..., -3.8605e-03,
          -1.1747e+01, -1.2942e+01],
         [-1.7825e+01, -9.5624e+00, -1.0534e+01,  ..., -2.3723e+01,
          -1.4789e+01, -9.0362e+00],
         [-8.2903e+00, -4.1952e+00, -4.1545e+00,  ..., -9.7267e+00,
          -3.3541e-01, -9.7657e+00],
         ...,
         [        nan,         nan,         nan,  ...,         nan,
                  nan,         nan],
         [        nan,         nan,         nan,  ...,         nan,
                  nan,         nan],
         [        nan,         nan,         nan,  ...,         nan,
                  nan,         nan]]], device='cuda:0')
```

**Node description**

Node without problem:
Name : node A
- CPU: 2x 12 cœurs Broadwell à 2.1GHz
- Memory: 384 Go RAM 
- Carte Infiniband : 1 Mellanox FDR
- GPU: 4 GPU NVIDIA Tesla V100 SXM2 32GB HBM2
- OS : CentOS 7

Node with problem:
Name: node B
- CPU: 2x 24 cores Icelake à 2.8GHz
-  Memory: 1 To RAM
-  Carte Infiniband : 1 Mellanox FDR
- GPU: 8 GPU NVIDIA Tesla A30 24GB
- OS : CentOS 7

I am running exactly the same code with the same conda environment. 

In the conda environment the versions are:

```
print(gpytorch.__version__)
1.6.0
```
```
print(torch.__version__)
1.11.0
```

Cuda version between both GPU nodes are exactly the same.

```
torch.version.cuda
'11.5'
```

Do you already have a similar problem: running exactly the same code with same software versions in different hardware resources ?

Thanks for your help !

Valentine

**Comment by gpleiss** [comment]
I don't think this is a bug per se (and I'm very confident it's not a bug on gpytorch's end). It is likely that your model is prone to numerical instabilities, and rounding errors could be different on different hardware.
