### ISSUE TITLE
[Question] Incompatible matrix sizes for `cholesky_solve`

### ISSUE THREAD

**Issue by murakrishn** [cornellius-gp/gpytorch#2097]
Hi,

I am trying to replicate a simple GP regression on a 1-dimensional function, closely following [GPyTorch's tutorial on Basic GP Regression](https://github.com/cornellius-gp/gpytorch/blob/master/examples/00_Basic_Usage/Metrics.ipynb). 

The code to reproduce the error is as follows:

```
import gpytorch as gpt
import torch as th
import numpy as np

def set_seed(seed=1729):
    np.random.seed(seed)
    th.manual_seed(seed)
    

class GPmodel(gpt.models.ExactGP):

    def __init__(self, train_x, train_y, likelihood):
        super().__init__(train_x, train_y, likelihood)
        self.mean_module = gpt.means.ConstantMean()
        self.covar_module = gpt.kernels.ScaleKernel(gpt.kernels.RBFKernel())

    def forward(self, x):
        mean = self.mean_module(x)
        covar = self.covar_module(x)
        return gpt.distributions.MultivariateNormal(mean, covar)


def func(X):
    return 4. * (1. - th.sin(6. * X + 8. * th.exp(6. * X - 7.)))



if __name__ == "__main__":
    test_x = th.linspace(0, 1, 100)[:,None]
    test_y = func(test_x)

    num_init = 3
    init_x = np.random.random(num_init)[:,None]
    init_x = th.tensor(init_x, dtype=th.float)
    init_y = func(init_x)

    # Define a GPyTorch model
    likelihood = gpt.likelihoods.GaussianLikelihood()
    model = GPmodel(init_x, init_y, likelihood)
    model_hypers = {
        "likelihood.noise_covar.noise": th.tensor(1e-4),
        "covar_module.base_kernel.lengthscale": th.tensor(0.15),
        "covar_module.outputscale": th.tensor(4.),
    }
    model.initialize(**model_hypers)

    # Check the model before training
    model.eval()
    with th.no_grad():
        observed_pred = model.likelihood(model(test_x))
```

However, as I run the code I face the following error:

```
Traceback (most recent call last):
  File "C:\...\site-packages\gpytorch\models\exact_prediction_strategies.py", line 44, in __init__
    train_labels = train_labels.reshape(
RuntimeError: shape '[3, 3]' is invalid for input of size 3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bgo_gpytorch.py", line 72, in <module>
    observed_pred = likelihood(model(test_x))
  File "C:\Users\...\site-packages\gpytorch\models\exact_gp.py", line 283, in __call__
    self.prediction_strategy = prediction_strategy(
  File "C:\Users\...\site-packages\gpytorch\models\exact_prediction_strategies.py", line 34, in prediction_strategy
    return cls(train_inputs, train_prior_dist, train_labels, likelihood)
  File "C:\Users\...\site-packages\gpytorch\kernels\scale_kernel.py", line 124, in prediction_strategy
    return self.base_kernel.prediction_strategy(train_inputs, train_prior_dist, train_labels, likelihood)
  File "C:\Users\...\site-packages\gpytorch\kernels\kernel.py", line 358, in prediction_strategy
    return exact_prediction_strategies.DefaultPredictionStrategy(
  File "C:\Users\...\site-packages\gpytorch\models\exact_prediction_strategies.py", line 48, in __init__
    raise RuntimeError(
RuntimeError: Flattening the training labels failed. The most common cause of this error is that the shapes of the prior mean and the training labels are mismatched. The shape of the train targets is torch.Size([3, 1]), while the reported shape of the mean is torch.Size([3]).
```

I found #1903 where a similar issue occurred and I modified the `forward()` method of the `GPmodel()` as to what was discussed in the referenced issue thread. The new `forward()` method is as follows:

```
...
    def forward(self, x):
        mean = self.mean_module(x)[:,None]
        covar = self.covar_module(x)
        return gpt.distributions.MultivariateNormal(mean, covar)
```

However, I am faced with a new error about incompatible matrix sizes for `cholesky_solve` and this is my terminal output :

```
Traceback (most recent call last):
  File "bgo_gpytorch.py", line 72, in <module>
    observed_pred = likelihood(model(test_x))
  File "C:\Users\...\site-packages\gpytorch\models\exact_gp.py", line 319, in __call__
    predictive_mean, predictive_covar = self.prediction_strategy.exact_prediction(full_mean, full_covar)
  File "C:\Users\...\site-packages\gpytorch\models\exact_prediction_strategies.py", line 271, in exact_prediction
    self.exact_predictive_mean(test_mean, test_train_covar),
  File "C:\Users\...\gpytorch\models\exact_prediction_strategies.py", line 289, in exact_predictive_mean
    res = (test_train_covar @ self.mean_cache.unsqueeze(-1)).squeeze(-1)
  File "C:\Users\...\site-packages\gpytorch\utils\memoize.py", line 59, in g
    return _add_to_cache(self, cache_name, method(self, *args, **kwargs), *args, kwargs_pkl=kwargs_pkl)
  File "C:\Users\...\site-packages\gpytorch\models\exact_prediction_strategies.py", line 238, in mean_cache
    mean_cache = train_train_covar.evaluate_kernel().inv_matmul(train_labels_offset).squeeze(-1)
  File "C:\Users\...\site-packages\gpytorch\lazy\lazy_tensor.py", line 1217, in inv_matmul
    return func.apply(self.representation_tree(), False, right_tensor, *self.representation())
  File "C:\Users\...\site-packages\gpytorch\functions\_inv_matmul.py", line 53, in forward
    solves = _solve(lazy_tsr, right_tensor)
  File "C:\Users\...\site-packages\gpytorch\functions\_inv_matmul.py", line 17, in _solve
    return lazy_tsr.cholesky()._cholesky_solve(rhs)
  File "C:\Users\...\site-packages\gpytorch\lazy\triangular_lazy_tensor.py", line 69, in _cholesky_solve
    res = self._tensor._cholesky_solve(rhs=rhs, upper=upper)
  File "C:\Users\...\site-packages\gpytorch\lazy\non_lazy_tensor.py", line 28, in _cholesky_solve
    return torch.cholesky_solve(rhs, self.evaluate(), upper=upper)
RuntimeError: Incompatible matrix sizes for cholesky_solve: each A matrix is 3 by 3 but each b matrix is 1 by 1
```

I have two questions,

- Why do I have to reshape the output from `self.mean_module`? While it was commented on in #1903, I don't completely follow, as I do not have a batch observation here.
- I am not able to narrow down on why I am facing the `cholesky_solve` issue. I would really appreciate any help in resolving this error.

Thank you so much for your time!

**Comment by murakrishn** [comment]
I was able to resolve the issue by not unsqueezing the inputs to the model. i.e.,

```
...
test_x = th.linspace(0, 1, 100)[:,None]
...
init_x = np.random.random(num_init)[:,None]
...
```

to
```
...
test_x = th.linspace(0, 1, 100)
...
init_x = np.random.random(num_init)
...
```
