### ISSUE TITLE
DKLModel with CPU

### ISSUE THREAD

**Issue by MaxCamPi** [cornellius-gp/gpytorch#210]
I am running the Large_Scale_Stochastic_Variational_DKL_Regression example, but on a much smaller data set (with smaller batch_size) on a CPU. All is fine until:

model = DKLModel(feature_extractor, n_features=num_features).cpu()

The output I get is:

Traceback (most recent call last):

  File "<ipython-input-92-7e8004762e22>", line 15, in <module>
    model = DKLModel(feature_extractor, n_features=num_features).cpu()

  File "<ipython-input-92-7e8004762e22>", line 5, in __init__
    self.gp_layer = GPRegressionLayer()

  File "<ipython-input-81-90816b0b2525>", line 8, in __init__
    parameter=torch.nn.Parameter(torch.Tensor([0]))

TypeError: register_parameter() got an unexpected keyword argument 'parameter'

Could you please tell if I am doing something wrong and how can I make this work?

Thank you!

**Comment by MaxCamPi** [comment]
Fixed after reinstalling gpytorch.
