### ISSUE TITLE
[Bug] Error while running MultiGPU examples

### ISSUE THREAD

**Issue by liyufan** [cornellius-gp/gpytorch#2246]
# 🐛 Bug

## To reproduce
Simply run this [MultiGPU example](https://github.com/cornellius-gp/gpytorch/tree/master/examples/02_Scalable_Exact_GPs/Simple_MultiGPU_GP_Regression.ipynb).

** Stack trace/error message **
```
Traceback (most recent call last):
  File "/tmp/ipykernel_7714/4130572758.py", line 3, in <module>
    model, likelihood = train(train_x, train_y,
  File "/tmp/ipykernel_7714/2210993840.py", line 44, in train
    loss = closure()
  File "/tmp/ipykernel_7714/2210993840.py", line 41, in closure
    loss = -mll(output, train_y)
  File "~/anaconda3/envs/torch/lib/python3.10/site-packages/gpytorch/module.py", line 30, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "~/anaconda3/envs/torch/lib/python3.10/site-packages/gpytorch/mlls/exact_marginal_log_likelihood.py", line 64, in forward
    res = output.log_prob(target)
  File "~/anaconda3/envs/torch/lib/python3.10/site-packages/gpytorch/distributions/multivariate_normal.py", line 193, in log_prob
    inv_quad, logdet = covar.inv_quad_logdet(inv_quad_rhs=diff.unsqueeze(-1), logdet=True)
  File "~/anaconda3/envs/torch/lib/python3.10/site-packages/linear_operator/operators/_linear_operator.py", line 1641, in inv_quad_logdet
    preconditioner, precond_lt, logdet_p = self._preconditioner()
  File "~/anaconda3/envs/torch/lib/python3.10/site-packages/linear_operator/operators/added_diag_linear_operator.py", line 114, in _preconditioner
    self._piv_chol_self = self._linear_op.pivoted_cholesky(rank=max_iter)
  File "~/anaconda3/envs/torch/lib/python3.10/site-packages/linear_operator/operators/_linear_operator.py", line 1849, in pivoted_cholesky
    res, pivots = func(self.representation_tree(), rank, error_tol, *self.representation())
  File "~/anaconda3/envs/torch/lib/python3.10/site-packages/torch/autograd/function.py", line 453, in apply
    return super().apply(*args, **kwargs)
  File "~/anaconda3/envs/torch/lib/python3.10/site-packages/linear_operator/functions/_pivoted_cholesky.py", line 72, in forward
    row = apply_permutation(matrix, pi_m.unsqueeze(-1), right_permutation=None).squeeze(-2)
  File "~/anaconda3/envs/torch/lib/python3.10/site-packages/linear_operator/utils/permutation.py", line 79, in apply_permutation
    return to_dense(matrix.__getitem__((*batch_idx, left_permutation.unsqueeze(-1), right_permutation.unsqueeze(-2))))
  File "~/anaconda3/envs/torch/lib/python3.10/site-packages/linear_operator/operators/_linear_operator.py", line 2691, in __getitem__
    res = self._get_indices(new_row_index, new_col_index, *new_batch_indices)
  File "~/anaconda3/envs/torch/lib/python3.10/site-packages/linear_operator/operators/cat_linear_operator.py", line 205, in _get_indices
    res_list = [
  File "~/anaconda3/envs/torch/lib/python3.10/site-packages/linear_operator/operators/cat_linear_operator.py", line 206, in <listcomp>
    linear_op._get_indices(sub_index[-2], sub_index[-1], *sub_index[:-2])
  File "~/anaconda3/envs/torch/lib/python3.10/site-packages/linear_operator/operators/dense_linear_operator.py", line 41, in _get_indices
    res = self.tensor[(*batch_indices, row_index, col_index)]
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cuda:1)
```

## Expected Behavior

This example should work fine.
## System information

**Please complete the following information:**
- GPyTorch Version: 1.9.1
- PyTorch Version: 1.13.1
- Computer OS: Ubuntu Server 22.04.1 LTS

## Additional context
The error message is same as #2216, but I don't think downgrade version of PyTorch is a good idea. In [changelog](https://github.com/pytorch/pytorch/releases/tag/v1.13.0) of PyTorch 1.13.0, it will throw an error on indexing a cpu tensor with non-cpu indices:
>Prior to 1.13, `cpu_tensor[cuda_indices]` was a valid program that would return a cpu tensor. The original use case for mixed device indexing was for `non_cpu_tensor[cpu_indices]`, and allowing the opposite was unintentional (`cpu_tensor[non_cpu_indices]`). This behavior appears to be rarely used, and a refactor of our indexing kernels made it difficult to represent an op that takes in (cpu_tensor, non_cpu_tensor) and returns another cpu_tensor, so it is now an error.
To replicate the old behavior for `base[indices]`, you can ensure that either `indices` lives on the CPU device, or `base` and `indices` both live on the same device.

Any hope to fix this?

**Comment by gpleiss** [comment]
@liyufan - would you be able to put up a PR to fix this?
