### ISSUE TITLE
[Docs] Fully Bayesian GPs example - crashes with obscure error 

### ISSUE THREAD

**Issue by vr308** [cornellius-gp/gpytorch#2337]
This example from the docs gives an obscure error - perhaps something trivial is missing?

```
import math
import torch
import gpytorch
import pyro
from pyro.infer.mcmc import NUTS, MCMC, HMC
from matplotlib import pyplot as plt

# Training data is 11 points in [0,1] inclusive regularly spaced
train_x = torch.linspace(0, 1, 4)
# True function is sin(2*pi*x) with Gaussian noise
train_y = torch.sin(train_x * (2 * math.pi)) + torch.randn(train_x.size()) * 0.2

# We will use the simplest form of GP model, exact inference
class ExactGPModel(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood):
        super(ExactGPModel, self).__init__(train_x, train_y, likelihood)
        self.mean_module = gpytorch.means.ConstantMean()
        self.covar_module = gpytorch.kernels.ScaleKernel(gpytorch.kernels.RBFKernel())

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)
    
# this is for running the notebook in our testing framework
import os
smoke_test = ('CI' in os.environ)
num_samples = 2 if smoke_test else 100
warmup_steps = 2 if smoke_test else 100


from gpytorch.priors import LogNormalPrior, NormalPrior, UniformPrior
# Use a positive constraint instead of usual GreaterThan(1e-4) so that LogNormal has support over full range.
likelihood = gpytorch.likelihoods.GaussianLikelihood(noise_constraint=gpytorch.constraints.Positive())
model = ExactGPModel(train_x, train_y, likelihood)

model.mean_module.register_prior("mean_prior", NormalPrior(-1, 1), "constant")
model.covar_module.base_kernel.register_prior("lengthscale_prior", UniformPrior(0.01, 0.5), "lengthscale")
model.covar_module.register_prior("outputscale_prior", UniformPrior(1, 2), "outputscale")
likelihood.register_prior("noise_prior", NormalPrior(0.01, 0.5), "noise")

mll = gpytorch.mlls.ExactMarginalLogLikelihood(likelihood, model)

def pyro_model(x, y):
    with gpytorch.settings.fast_computations(False, False, False):
        sampled_model = model.pyro_sample_from_prior()
        output = sampled_model.likelihood(sampled_model(x))
        pyro.sample("obs", output, obs=y)
    return y

nuts_kernel = NUTS(pyro_model)
mcmc_run = MCMC(nuts_kernel, num_samples=num_samples, warmup_steps=warmup_steps, disable_progbar=smoke_test)
mcmc_run.run(train_x, train_y)    
```
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/home/vr308/Desktop/Workspace/Kernel-Learning-with-Latent-GPs/untitled0.py", line 61, in <module>
    mcmc_run.run(train_x, train_y)

  File "/home/vr308/anaconda3/envs/base_env/lib/python3.8/site-packages/pyro/poutine/messenger.py", line 12, in _context_wrap
    return fn(*args, **kwargs)

  File "/home/vr308/anaconda3/envs/base_env/lib/python3.8/site-packages/pyro/infer/mcmc/api.py", line 563, in run
    for x, chain_id in self.sampler.run(*args, **kwargs):

  File "/home/vr308/anaconda3/envs/base_env/lib/python3.8/site-packages/pyro/infer/mcmc/api.py", line 223, in run
    for sample in _gen_samples(

  File "/home/vr308/anaconda3/envs/base_env/lib/python3.8/site-packages/pyro/infer/mcmc/api.py", line 144, in _gen_samples
    kernel.setup(warmup_steps, *args, **kwargs)

  File "/home/vr308/anaconda3/envs/base_env/lib/python3.8/site-packages/pyro/infer/mcmc/hmc.py", line 345, in setup
    self._initialize_model_properties(args, kwargs)

  File "/home/vr308/anaconda3/envs/base_env/lib/python3.8/site-packages/pyro/infer/mcmc/hmc.py", line 279, in _initialize_model_properties
    init_params, potential_fn, transforms, trace = initialize_model(

  File "/home/vr308/anaconda3/envs/base_env/lib/python3.8/site-packages/pyro/infer/mcmc/util.py", line 427, in initialize_model
    max_plate_nesting = _guess_max_plate_nesting(model, model_args, model_kwargs)

  File "/home/vr308/anaconda3/envs/base_env/lib/python3.8/site-packages/pyro/infer/mcmc/util.py", line 251, in _guess_max_plate_nesting
    model_trace = poutine.trace(model).get_trace(*args, **kwargs)

  File "/home/vr308/anaconda3/envs/base_env/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py", line 198, in get_trace
    self(*args, **kwargs)

  File "/home/vr308/anaconda3/envs/base_env/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py", line 180, in __call__
    raise exc from e

  File "/home/vr308/anaconda3/envs/base_env/lib/python3.8/site-packages/pyro/poutine/trace_messenger.py", line 174, in __call__
    ret = self.fn(*args, **kwargs)

  File "/home/vr308/Desktop/Workspace/Kernel-Learning-with-Latent-GPs/untitled0.py", line 54, in pyro_model
    sampled_model = model.pyro_sample_from_prior()

  File "/home/vr308/anaconda3/envs/base_env/lib/python3.8/site-packages/gpytorch/module.py", line 383, in pyro_sample_from_prior
    return _pyro_sample_from_prior(module=new_module, memo=None, prefix="")

  File "/home/vr308/anaconda3/envs/base_env/lib/python3.8/site-packages/gpytorch/module.py", line 493, in _pyro_sample_from_prior
    _pyro_sample_from_prior(module=module_, memo=memo, prefix=submodule_prefix)

  File "/home/vr308/anaconda3/envs/base_env/lib/python3.8/site-packages/gpytorch/module.py", line 488, in _pyro_sample_from_prior
    value = pyro.sample(prefix + ("." if prefix else "") + prior_name, prior)

  File "/home/vr308/anaconda3/envs/base_env/lib/python3.8/site-packages/pyro/primitives.py", line 163, in sample
    apply_stack(msg)

  File "/home/vr308/anaconda3/envs/base_env/lib/python3.8/site-packages/pyro/poutine/runtime.py", line 218, in apply_stack
    default_process_message(msg)

  File "/home/vr308/anaconda3/envs/base_env/lib/python3.8/site-packages/pyro/poutine/runtime.py", line 179, in default_process_message
    msg["value"] = msg["fn"](*msg["args"], **msg["kwargs"])

  File "/home/vr308/anaconda3/envs/base_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)

  File "/home/vr308/anaconda3/envs/base_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 201, in _forward_unimplemented
    raise NotImplementedError(f"Module [{type(self).__name__}] is missing the required \"forward\" function")

NotImplementedError: Module [NormalPrior] is missing the required "forward" function
Trace Shapes:
 Param Sites:
Sample Sites:
```

**Comment by tomiesm** [comment]
The issue still exists - I also get an error. Please review the example in documentation.
