### ISSUE TITLE
Pyinstaller with gpytorch

### ISSUE THREAD

**Issue by PMoldtmann** [cornellius-gp/gpytorch#2347]
# 🐛 Bug

## To reproduce

** Code snippet to reproduce **

in "main.py"
```
import customtkinter as ctk
import gpytorch
import torch

class GUI(ctk.CTk):
    def __init__(self):
        super().__init__()
GUI()
```
then compiled with
```
python -m PyInstaller -w --add-binary "icon.ico;." main.py --collect-all customtkinter --hidden-import PIL 
```
I've tried adding
```
--collect-all gpytorch --collect-all torch --hidden-import gpytorch
```
but no joy.

** Stack trace/error message **
```
Traceback (most recent call last):
  File "torch\_sources.py", line 21, in get_source_lines_and_file
    sourcelines, file_lineno = inspect.getsourcelines(obj)
  File "inspect.py", line 979, in getsourcelines
  File "inspect.py", line 798, in findsource
OSError: could not get source code

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "gpytorch\__init__.py", line 5, in <module>
    import linear_operator
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "linear_operator\__init__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "linear_operator\operators\__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "linear_operator\operators\_linear_operator.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "linear_operator\utils\__init__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "linear_operator\utils\contour_integral_quad.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "linear_operator\utils\linear_cg.py", line 17, in <module>
  File "torch\jit\_script.py", line 1340, in script
    ast = get_jit_def(obj, obj.__name__)
  File "torch\jit\frontend.py", line 234, in get_jit_def
    parsed_def = parse_def(fn)
  File "torch\_sources.py", line 96, in parse_def
    sourcelines, file_lineno, filename = get_source_lines_and_file(fn, ErrorReport.call_stack())
  File "torch\_sources.py", line 28, in get_source_lines_and_file
    raise OSError(msg) from e
OSError: Can't get source for <function _jit_linear_cg_updates at 0x000001CDC147FC10>. TorchScript requires source access in order to carry out compilation, make sure original .py files are available.

```

## System information

**Please complete the following information:**
-  1.10
-  1.12.1
-  Windows 11 Home 64bit
-  3.8.16

## Additional context
Everything is freshly set up in conda.

Thank you!

**Comment by PMoldtmann** [comment]
Trying to add
```
from PyInstaller.utils.hooks import collect_data_files

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=binaries,
    datas=[datas,*collect_data_files("linear_operator",include_py_files=True)],
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
```
raises the warnings below before crashing when trying to compile by
´´´
python -m PyInstaller main.spec
´´´
´´´
25408 WARNING: Unable to find package for requirement scikit-learn from package gpytorch.
25408 INFO: Packages required by gpytorch:
['linear_operator']
2661 WARNING: Failed to collect submodules for 'torch.utils.tensorboard' because importing 'torch.utils.sensorboard' raised: ModuleNotFoundError: No module named 'tensorboard'
´´´

**Comment by PMoldtmann** [comment]
I added to main.spec:
```
import gpytorch
import inspect

def collect_source_files(modules):
    datas = []
    for module in modules:
        source = inspect.getsourcefile(module)
        dest = f"src.{module.__name__}"  # use "src." prefix
        datas.append((source, dest))
    return datas

source_files = collect_source_files([gpytorch])  # return same structure as `collect_data_files()`
source_files_toc = TOC((name, path, 'DATA') for path, name in source_files)
```

and changed "get_source" in "pyimod2_importers.py" to:
```
def get_source(self, fullname):
        """
        Method should return the source code for the module as a string.
        But frozen modules does not contain source code.

        Return None.
        """
        if fullname in self.toc:
            sourcename = f"src.{fullname}"
            if sourcename in self.toc:
                return self._pyz_archive.extract(sourcename)[1].decode("utf-8")
            return None
        else:
            # ImportError should be raised if module not found.
            raise ImportError('No module named ' + fullname)
```
As suggested in https://github.com/pyinstaller/pyinstaller/issues/4764#issuecomment-726668800

and now get a differnt error return:
```
Traceback (most recent call last):
  File "C:\Users\pHiLi\pyinstaller\PyInstaller\hooks\rthooks\pyi_rth_win32comgenpy.py", line 40, in <module>
    import win32com  # noqa: E402
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "win32com\__init__.py", line 5, in <module>
ModuleNotFoundError: No module named 'win32api'

```

**Comment by PMoldtmann** [comment]
Adding
```
import os
os.environ["PYTORCH_JIT"] = "0"
```
to my main.py also didn't do anything

**Comment by PMoldtmann** [comment]
> I don't know if this is a bug on our end. Can you open up a [discussion](https://github.com/cornellius-gp/gpytorch/discussions) instead?

Actually I don't think it was, I've logged the steps that got it working below, maybe that helps someone in the future.

- Create a new env in python 3.8.16
- ```pip install customtkinter```
- ```conda install -c anaconda openpyxl```
- ```conda install -c conda-forge xlsxwriter```
- ```conda install -c anaconda pillow```
- ```conda install -c anaconda pandas```
- ```conda install botorch -c pytorch -c gpytorch -c conda-forge```
- ```conda install -c conda-forge pyinstaller```
- install latest dev build 
```
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```
- compiled with 
```
python -m PyInstaller -w --add-binary "icon.ico;." main.py --collect-all customtkinter --hidden-import PIL --collect-all linear_operator --hidden-import openpyxl.cell._writer --hidden-import cudatoolkit --hidden-import torchvision --collect-all torch --collect-all tkinter
```
- I wanted to export it as a compressed exe but ```-F``` returns ```Failed to extract cublas64_11.dll: decompression resulted in return code -1!``` **This is likely an issue in pyinstaller side, I'm still on it**
