### ISSUE TITLE
[Bug] Numerical Instability in Gaussian Quadrature for GP Classification

### ISSUE THREAD

**Issue by kayween** [cornellius-gp/gpytorch#2596]
# 🐛 Bug

The GP classification model with Bernoulli likelihood is not numerically stable on GPUs. In particular, the backward pass of `gpytorch.functions._log_normal_cdf` fails.

## To reproduce

**Code snippet to reproduce**
```python
import torch
import gpytorch

from gpytorch.models import ApproximateGP
from gpytorch.variational import CholeskyVariationalDistribution
from gpytorch.variational import VariationalStrategy


class GPClassificationModel(ApproximateGP):
    def __init__(self, inducing_points):
        variational_distribution = CholeskyVariationalDistribution(inducing_points.size(0))
        variational_strategy = VariationalStrategy(
            self, inducing_points, variational_distribution, learn_inducing_locations=False,
        )
        super().__init__(variational_strategy)

        self.mean_module = gpytorch.means.ConstantMean()
        self.covar_module = gpytorch.kernels.ScaleKernel(gpytorch.kernels.RBFKernel())

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultivariateNormal(mean_x, covar_x)


device = "cuda:0"

torch.manual_seed(0)
torch.set_default_dtype(torch.float64)
# torch.use_deterministic_algorithms(True)

n = 50000

train_x = torch.linspace(0., 2., n).unsqueeze(-1).to(device)
train_y = torch.rand(n).bernoulli().to(train_x)

inducing_points = torch.linspace(0, 2., 10).to(device)

likelihood = gpytorch.likelihoods.BernoulliLikelihood()
model = GPClassificationModel(inducing_points=inducing_points)

model.train().to(device)
likelihood.train().to(device)

optimizer = torch.optim.Adam(model.parameters(), lr=0.1)
mll = gpytorch.mlls.VariationalELBO(likelihood, model, train_y.numel())

for i in range(500):
    optimizer.zero_grad()

    output = model(train_x)
    loss = -mll(output, train_y)
    loss.backward()

    print(
        "iter %3d," % (i + 1),
        "loss %.3f," % loss.item(),
        "mean %.3f" % model.mean_module.constant.item(),
        "os %.3f," % model.covar_module.outputscale.item(),
        "ls %.3f," % model.covar_module.base_kernel.lengthscale.item(),
        "avg mean %.3f," % model.variational_strategy.variational_distribution.mean.mean().item(),
        "avg var %.3f," % model.variational_strategy.variational_distribution.covariance_matrix.diag().mean().item(),
    )

    optimizer.step()
```

**Stack trace/error message**
```
iter   1, loss 0.908, mean 0.000 os 0.693, ls 0.693, avg mean 0.000, avg var 1.000,
Traceback (most recent call last):
  File "/home/kaiwen/Desktop/preferential-level-set-estimation/one_dimensional.py", line 53, in <module>
    loss.backward()
  File "/home/kaiwen/.local/lib/python3.12/site-packages/torch/_tensor.py", line 521, in backward
    torch.autograd.backward(
  File "/home/kaiwen/.local/lib/python3.12/site-packages/torch/autograd/__init__.py", line 289, in backward
    _engine_run_backward(
  File "/home/kaiwen/.local/lib/python3.12/site-packages/torch/autograd/graph.py", line 769, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kaiwen/.local/lib/python3.12/site-packages/torch/autograd/function.py", line 306, in apply
    return user_fn(self, *args)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/kaiwen/Desktop/preferential-level-set-estimation/packages/gpytorch/gpytorch/functions/_log_normal_cdf.py", line 109, in backward
    log_phi_z_grad[z_is_small] = torch.abs(ctx.denominator.div(ctx.numerator)).mul(math.sqrt(2 / math.pi))
    ~~~~~~~~~~~~~~^^^^^^^^^^^^
RuntimeError: shape mismatch: value tensor of shape [383130] cannot be broadcast to indexing result of shape [383132]
```

## Expected Behavior

The training should run without the error. In particular, `z_is_small` and `ctx.denominator` should have the same shape such that the assignment statement works out.

## System information

- PyTorch Version: 2.4.1+cu121
- GPyTorch Version: 1.14.dev0+g6cb2bb84.d20240913 (the commit corresponding to v1.13)
- OS Version: Fedora 40
- NVIDIA Driver Version: 560.35.03
- CUDA Version: 12.6

## Additional context
- The above code works fine on CPUs. The error only occurs on GPUs.
- The error also occurs, though less frequently, with fewer training data (e.g., `n = 500`).

**Comment by kayween** [comment]
I am going to close this issue. It appears that the bug was caused by a defective RTX 3080 GPU.

**Comment by kayween** [comment]
I am going to close this issue. It appears that the bug was caused by a defective RTX 3080 GPU.
