### ISSUE TITLE
Test failure in TestKissGPAdditiveClassification

### ISSUE THREAD

**Issue by Balandat** [cornellius-gp/gpytorch#334]
I'm seeing the below test failure on pytorch master. 

Looks like this is due to a discrepancy in the following two checks: 
https://github.com/cornellius-gp/gpytorch/blob/master/gpytorch/functions/_log_normal_cdf.py#L77
https://github.com/cornellius-gp/gpytorch/blob/master/gpytorch/functions/_log_normal_cdf.py#L108-L109

This is somewhat disconcerting b/c these should be the same tensors? 

```
AttributeError: 'LogNormalCDF' object has no attribute 'denominator'
  File "/usr/local/fbcode/gcc-5-glibc-2.23/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/fbcode/gcc-5-glibc-2.23/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/data/users/balandat/fbsource/fbcode/buck-out/dev-nosan/gen/pytorch/gpytorch/test_gpytorch_examples#binary,link-tree/test/examples/test_kissgp_additive_classification.py", line 76, in test_kissgp_classification_error
    loss.backward()
  File "/data/users/balandat/fbsource/fbcode/buck-out/dev-nosan/gen/pytorch/gpytorch/test_gpytorch_examples#binary,link-tree/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/data/users/balandat/fbsource/fbcode/buck-out/dev-nosan/gen/pytorch/gpytorch/test_gpytorch_examples#binary,link-tree/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/data/users/balandat/fbsource/fbcode/buck-out/dev-nosan/gen/pytorch/gpytorch/test_gpytorch_examples#binary,link-tree/gpytorch/functions/_log_normal_cdf.py", line 109, in backward
    log_phi_z_grad[z_is_small] = torch.abs(self.denominator.div(self.numerator)).mul(math.sqrt(2 / math.pi))
```

**Comment by jacobrgardner** [comment]
@Balandat I don't see this failure on the #335 branch -- maybe we can see if that fixes the issue once merged?

**Comment by Balandat** [comment]
Sounds good, I can try that. Do you expect this to be merged in soonish?

**Comment by Balandat** [comment]
I patched onto the PR, unfortunately I still see this error (and the one below).

```
      ✗ pytorch/gpytorch:test_gpytorch_examples - test_kissgp_gp_mean_abs_error (test.examples.test_kissgp_kronecker_product_regression.TestKissGPKroneckerProductRegression) 1.150s 1/1 (failed)
RuntimeError: cannot reshape tensor of 0 elements into shape [-1, 0, 0]
  File "/usr/local/fbcode/gcc-5-glibc-2.23/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/fbcode/gcc-5-glibc-2.23/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/data/users/balandat/fbsource/fbcode/buck-out/dev-nosan/gen/pytorch/gpytorch/test_gpytorch_examples#binary,link-tree/test/examples/test_kissgp_kronecker_product_regression.py", line 90, in test_ki
ssgp_gp_mean_abs_error
    loss = -mll(output, train_y)
  File "/data/users/balandat/fbsource/fbcode/buck-out/dev-nosan/gen/pytorch/gpytorch/test_gpytorch_examples#binary,link-tree/gpytorch/module.py", line 182, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/data/users/balandat/fbsource/fbcode/buck-out/dev-nosan/gen/pytorch/gpytorch/test_gpytorch_examples#binary,link-tree/gpytorch/mlls/exact_marginal_log_likelihood.py", line 31, in forward
    res = output.log_prob(target)
  File "/data/users/balandat/fbsource/fbcode/buck-out/dev-nosan/gen/pytorch/gpytorch/test_gpytorch_examples#binary,link-tree/gpytorch/distributions/multivariate_normal.py", line 123, in log_prob
    inv_quad, log_det = covar.inv_quad_log_det(inv_quad_rhs=diff.unsqueeze(-1), log_det=True)
  File "/data/users/balandat/fbsource/fbcode/buck-out/dev-nosan/gen/pytorch/gpytorch/test_gpytorch_examples#binary,link-tree/gpytorch/lazy/lazy_tensor.py", line 629, in inv_quad_log_det
    preconditioner=self._preconditioner()[0],
  File "/data/users/balandat/fbsource/fbcode/buck-out/dev-nosan/gen/pytorch/gpytorch/test_gpytorch_examples#binary,link-tree/gpytorch/lazy/added_diag_lazy_tensor.py", line 48, in _preconditioner
    self._woodbury_cache = pivoted_cholesky.woodbury_factor(self._piv_chol_self, self._diag_tensor.diag())
  File "/data/users/balandat/fbsource/fbcode/buck-out/dev-nosan/gen/pytorch/gpytorch/test_gpytorch_examples#binary,link-tree/gpytorch/utils/pivoted_cholesky.py", line 95, in woodbury_factor
    R = batch_potrs(low_rank_mat, batch_potrf(shifted_mat))
  File "/data/users/balandat/fbsource/fbcode/buck-out/dev-nosan/gen/pytorch/gpytorch/test_gpytorch_examples#binary,link-tree/gpytorch/utils/cholesky.py", line 14, in batch_potrf
    potrf_list = [sub_mat.potrf() for sub_mat in mat.view(-1, *mat.shape[-2:])]
```

**Comment by Balandat** [comment]
That's good, I guess. Will dig a little more, let me know if you run into similar failures.

**Comment by gpleiss** [comment]
Closing, unless there's still issues.

**Comment by h-jia** [comment]
Same issue with: cannot reshape tensor of 0 elements into shape.

Trained with batch size 1 `1 x b x n,` and test on batch size 1 `1 x b x n`.

Any possible reasons?

**Comment by h-jia** [comment]
```
Traceback (most recent call last):
  File "rrgp.py", line 165, in <module>
    preds = test(epoch)
  File "rrgp.py", line 155, in test
    preds = model(test_x)
  File "/anaconda3-server/lib/python3.6/site-packages/gpytorch/models/exact_gp.py", line 154, in __call__
    precomputed_cache=self.mean_cache,
  File "/anaconda3-server/lib/python3.6/site-packages/gpytorch/functions/__init__.py", line 89, in exact_predictive_mean
    return full_covar.exact_predictive_mean(full_mean, train_labels, num_train, likelihood, precomputed_cache)
  File "/anaconda3-server/lib/python3.6/site-packages/gpytorch/lazy/lazy_evaluated_kernel_tensor.py", line 174, in exact_predictive_mean
    full_mean, train_labels, num_train, likelihood, precomputed_cache
  File "/anaconda3-server/lib/python3.6/site-packages/gpytorch/lazy/interpolated_lazy_tensor.py", line 405, in exact_predictive_mean
    res = left_interp(test_interp_indices, test_interp_values, precomputed_cache).squeeze(-1) + test_mean
  File "/anaconda3-server/lib/python3.6/site-packages/gpytorch/utils/interpolation.py", line 197, in left_interp
    res = res.view(n_data, n_interp, -1)
RuntimeError: cannot reshape tensor of 0 elements into shape [0, 4, -1]
```

**Comment by gpleiss** [comment]
Hmmm I'll look into it tomorrow

**Comment by h-jia** [comment]
Thanks
