### ISSUE TITLE
Initializing GaussianLikelihood noise broken

### ISSUE THREAD

**Issue by KeAWang** [cornellius-gp/gpytorch#478]
```
>>> import gpytorch
>>> gl = gpytorch.likelihoods.GaussianLikelihood()
>>> gl.initialize(noise=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../gpytorch/gpytorch/module.py", line 89, in initialize
    setattr(self, name, val)
  File "../lib/python3.6/site-packages/torch/nn/modules/module.py", line 579, in __setattr__
    object.__setattr__(self, name, value)
  File ".../gpytorch/gpytorch/likelihoods/gaussian_likelihood.py", line 63, in noise
    self.noise_covar.initialize(value)
TypeError: initialize() takes 1 positional argument but 2 were given
```

raw_noise works though
```>>> gl.initialize(raw_noise=3)
GaussianLikelihood(
  (noise_covar): HomoskedasticNoise()
)```

**Comment by gpleiss** [comment]
We're open to a PR 😄
