### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by scigeek72** [cornellius-gp/gpytorch#684]
# 🐛 Bug

while replicating the simple gp regression tutorial, I am getting the following error: `AttributeError: module 'numpy.polynomial' has no attribute 'hermite'`. Below is the full code and the trace of the error.

Code

`likelihood = gpytorch.likelihoods.GaussianLikelihood()`

Trace

```
likelihood = gpytorch.likelihoods.GaussianLikelihood()
Traceback (most recent call last):

  File "<ipython-input-120-8d8331bb886d>", line 1, in <module>
    likelihood = gpytorch.likelihoods.GaussianLikelihood()

  File "/anaconda3/envs/py36/lib/python3.6/site-packages/gpytorch/likelihoods/gaussian_likelihood.py", line 62, in __init__
    super().__init__(noise_covar=noise_covar)

  File "/anaconda3/envs/py36/lib/python3.6/site-packages/gpytorch/likelihoods/gaussian_likelihood.py", line 24, in __init__
    super().__init__()

  File "/anaconda3/envs/py36/lib/python3.6/site-packages/gpytorch/likelihoods/likelihood.py", line 48, in __init__
    self.quadrature = GaussHermiteQuadrature1D()

  File "/anaconda3/envs/py36/lib/python3.6/site-packages/gpytorch/utils/quadrature.py", line 24, in __init__
    locations, weights = self._locs_and_weights(num_locs)

  File "/anaconda3/envs/py36/lib/python3.6/site-packages/gpytorch/utils/quadrature.py", line 41, in _locs_and_weights
    locations, weights = np.polynomial.hermite.hermgauss(num_locs)

AttributeError: module 'numpy.polynomial' has no attribute 'hermite'
```

**Comment by jacobrgardner** [comment]
@scigeek72 Everything works for me on `numpy == 1.16.2`. Can you try:
```python
from numpy.polynomial import hermite
```
In an ipython prompt? I think your installed version of numpy may just be really old.

**Comment by scigeek72** [comment]
Yes, you are right. It was the old numpy issue. Thanks for clarification.
