### ISSUE TITLE
[Bug] Issue with double and spectral mixture kernel

### ISSUE THREAD

**Issue by wtstephe** [cornellius-gp/gpytorch#837]
# 🐛 Bug

When initializing a spectral mixture kernel using initialize_from_data() with data of type torch.DoubleTensor, the initialization crashes. I think the problem is the line in spectral_mixture_kernel.py, which always creates a tensor of type torch.FloatTensor:

```python
min_dist = torch.zeros(1, self.ard_num_dims)
```
The following fixed this for me:
```python
min_dist = torch.zeros(1, self.ard_num_dims).type(train_x.type())
```

## To reproduce

```python
import torch
import gpytorch

X = torch.sin(torch.linspace(0,1)).double()
Y = torch.sin(torch.linspace(0,1)).double() + 4.5

covar_module = gpytorch.kernels.SpectralMixtureKernel(num_mixtures=10)
covar_module.double()
covar_module.initialize_from_data(X, Y)

```
Error message:
```
Traceback (most recent call last):
  File "breakSpectralMixtureKernel.py", line 9, in <module>
    covar_module.initialize_from_data(X, Y)
  File "/home/will/anaconda3/lib/python3.6/site-packages/gpytorch-0.3.3-py3.6.egg/gpytorch/kernels/spectral_mixture_kernel.py", line 163, in initialize_from_data
RuntimeError: output with backend CPU and dtype Float doesn't match the desired backend CPU and dtype Double
```

**Comment by KeAWang** [comment]
I see that you are still using gpytorch 0.3.3. You should update your package version since this bug was fixed by #737
