### ISSUE TITLE
[Bug] Attribute error on pip install from master

### ISSUE THREAD

**Issue by fonnesbeck** [cornellius-gp/gpytorch#926]
I'm using `pip` to install gpytorch from master, following the instructions on the README. However, it fails with the following:

```
>>> pip install git+https://github.com/cornellius-gp/gpytorch.git
Collecting git+https://github.com/cornellius-gp/gpytorch.git
  Cloning https://github.com/cornellius-gp/gpytorch.git to /tmp/pip-req-build-in2qhkf9
  Running command git clone -q https://github.com/cornellius-gp/gpytorch.git /tmp/pip-req-build-in2qhkf9
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/anaconda3/bin/python /opt/anaconda3/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-h_e568c_/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (14 lines):
  Traceback (most recent call last):
    File "/opt/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/opt/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/opt/anaconda3/lib/python3.7/site-packages/pip/__main__.py", line 16, in <module>
      from pip._internal import main as _main  # isort:skip # noqa
    File "/opt/anaconda3/lib/python3.7/site-packages/pip/_internal/__init__.py", line 4, in <module>
      import locale
    File "/opt/anaconda3/lib/python3.7/locale.py", line 16, in <module>
      import re
    File "/opt/anaconda3/lib/python3.7/re.py", line 143, in <module>
      class RegexFlag(enum.IntFlag):
  AttributeError: module 'enum' has no attribute 'IntFlag'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/anaconda3/bin/python /opt/anaconda3/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-h_e568c_/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.
```

Installing onto a GCS instance.

**Comment by Balandat** [comment]
Do you have some other `enum` masking the builtin enum? See https://stackoverflow.com/a/45716067 for discussion of this.

Maybe try installing in a clean environment?

**Comment by fonnesbeck** [comment]
My enum is:

    /opt/anaconda3/lib/python3.7/enum.py
