### ISSUE TITLE
AttributeError: 'VariationalStrategy' object has no attribute 'size' [Bug]

### ISSUE THREAD

**Issue by PingjunChen** [cornellius-gp/gpytorch#979]
# 🐛 AttributeError: 'VariationalStrategy' object has no attribute 'size'

I tried to follow the tutorial `Simple_GP_Classification.ipynb` in `gpytorch/examples/02_Simple_GP_Classification/` and copied the code to my script to run. I came across the problem of using `VariationalStrategy`.

## To reproduce

** Code snippet to reproduce **
```python
import math
import torch
import gpytorch
from gpytorch.models import VariationalGP
from gpytorch.variational import CholeskyVariationalDistribution
from gpytorch.variational import VariationalStrategy


train_x = torch.linspace(0, 1, 10)
train_y = torch.sign(torch.cos(train_x * (4 * math.pi))).add(1).div(2)

class GPClassificationModel(VariationalGP):
    def __init__(self, train_x):
        variational_distribution = CholeskyVariationalDistribution(train_x.size(0))
        variational_strategy = VariationalStrategy(self, train_x, variational_distribution)
        super(GPClassificationModel, self).__init__(variational_strategy)
        self.mean_module = gpytorch.means.ConstantMean()
        self.covar_module = gpytorch.kernels.ScaleKernel(gpytorch.kernels.RBFKernel())

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        latent_pred = gpytorch.distributions.MultivariateNormal(mean_x, covar_x)
        return latent_pred

# Initialize model and likelihood
model = GPClassificationModel(train_x)
```

** Stack trace/error message **
```
Traceback (most recent call last):
  File "/home/pingjun/anaconda3/lib/python3.6/site-packages/gpytorch/module.py", line 291, in __getattr__
    return super().__getattribute__(name)
AttributeError: 'VariationalStrategy' object has no attribute 'size'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cls_sin.py", line 36, in <module>
    model = GPClassificationModel(train_x)
  File "cls_sin.py", line 24, in __init__
    super(GPClassificationModel, self).__init__(variational_strategy)
  File "/home/pingjun/anaconda3/lib/python3.6/site-packages/gpytorch/models/variational_gp.py", line 15, in __init__
    variational_distribution = CholeskyVariationalDistribution(train_input.size(0))
  File "/home/pingjun/anaconda3/lib/python3.6/site-packages/gpytorch/module.py", line 293, in __getattr__
    raise e
  File "/home/pingjun/anaconda3/lib/python3.6/site-packages/gpytorch/module.py", line 288, in __getattr__
    return super().__getattr__(name)
  File "/home/pingjun/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 585, in __getattr__
    type(self).__name__, name))
AttributeError: 'VariationalStrategy' object has no attribute 'size'
```

## System information
- GPyTorch Version: 0.3.6
- PyTorch Version: 1.3.1
- Computer OS: ubuntu 16.04 LTS

**Comment by gpleiss** [comment]
The example that you are referring to requires the master branch of gpytorch (pip install git+https://github.com/cornellius-gp/gpytorch.git). We will be cutting a new release shortly.

If you are on the master branch this issue goes away.
